### ISSUE TITLE
Support Eclipse

### ISSUE THREAD

**Issue by treyhunner** [editorconfig/editorconfig#108]
Create a plugin for eclipse

Should at least support:

- `indent_style`
- `indent_size`
- `tab_width` (if possible)

Preferably support:

- `trim_trailing_whitespace`
- `insert_final_newline`
- `end_of_line`
- `charset`

This issue has a **$140** bounty on [Freedom Sponsors](https://freedomsponsors.org/issue/271/support-eclipse) as of February 18, 2015

**Comment by treyhunner** [comment]
Copying @ncjones here because they noted in [this comment](https://github.com/editorconfig/editorconfig/issues/86#issuecomment-65743374) that they'd started an Eclipse plugin.

I was just asked last night why there was no Eclipse plugin yet.  I plan to advertise the Eclipse plugin [bounty](https://freedomsponsors.org/issue/271/support-eclipse) to bring more attention to it.

**Comment by JohnWu-Pro** [comment]
Just a reference: the AnyEdit tools plugin for Eclipse provides similar function but does not understand EditorConfig. I believe its code can be migrated here to compose the plugin here.

**Comment by danielgcf** [comment]
@treyhunner I started the plugin https://github.com/danielgcf/editorconfig-eclipse . I saw it on freedomsponsors.

**Comment by treyhunner** [comment]
@danielgcf excellent! :trophy:  I'll install Eclipse and test the supported properties today.

**Comment by treyhunner** [comment]
I couldn't figure out what I was doing.  I'll try to look at it again within the next few days.  It would be wonderful if an Eclipse-savvy user could take a look in the meantime. :sweat_smile:

**Comment by ncjones** [comment]
@danielgcf 
Thanks for pushing this along. Setting the global tab behavior was exactly the piece I was missing! I  hacked that into my plugin ([ncjones/editorconfig-eclipse](https://github.com/ncjones/editorconfig-eclipse)) on the "preferences-on-selection" branch and now the indent-size and style is correctly set for non-Java files! Still there's more work to do for Java files but I think the main hurdle has been overcome.

**Comment by danielgcf** [comment]
@ncjones NP. If you need any help just let me know.

**Comment by ncjones** [comment]
@danielgcf 
I've tidied up the changes and pushed them to master. I've added a bunch of items to TODO.md. Feel free to help out with any of the TODOs (particularly in the "required for v1.0" section).

The main issue is that the tab behaviour settings only seem to work in the text and xml editors, but not in the Java editor or the Ant editor (haven't tested other editors). The other significant issue is that trim trailing whitespace doesn't seem to work at all.

We can move this conversation to email if you want.

**Comment by treyhunner** [comment]
@ncjones @danielgcf it's great that you're both working on getting this plugin working!

Do you plan to merge your efforts into a single project?

If you start an email thread or issue, feel free to CC me.  I'd like to advertise a plugin on the website and promote it on Twitter as soon as we have a plan.

**Comment by danielgcf** [comment]
@ncjones @treyhunner I see no problems. we just need to sync that how it's going to work. I realized i did one thing completely different from what was expected because: first: i didn't know how the editorconfig works, secondly I was just aiming to set the eclipse properties.

I installed the sublime plugin them it became clearer how it works. I spent the day figuring out how can i do something similar in eclipse (once some behavior are a bit different). I will try to create a specif editor just for editconfig. I'll see if it works.

**Comment by ncjones** [comment]
@danielgcf @treyhunner Can you confirm you got my status update email?

**Comment by treyhunner** [comment]
@ncjones received the email. I'll be watching the thread.  Please call out my name it if you'd like me to address something specifically.  Thanks!

**Comment by ncjones** [comment]
I've created an update site which can be used to install the plugin from Eclipse:

     https://editorconfig-eclipse.github.io/repository

The current version (0.1.0) is incomplete (most notably, no support for Java editors) and has only been tested on Eclipse Luna. Please test and report issues at https://github.com/ncjones/editorconfig-eclipse/issues.

**Comment by tnguyen14** [comment]
@ncjones going to that address I got a page not found.

**Comment by ncjones** [comment]
@tnguyen14 It's the base URL for an Eclipse update site so you need to use it with the Eclipse Update Manager. I've added an index.html to the update site explaining this.

**Comment by ncjones** [comment]
I've added indent_style and indent_size support for Java and XML editors and released as version 0.2.0.

**Comment by ben-willow** [comment]
@ncjones, can you [sign each release](http://wiki.eclipse.org/JAR_Signing) so we can know provenance of future releases, and help protect against malicious updates?

**Comment by ncjones** [comment]
@ben-willow Thanks for the feedback. I'll sign the next release.

**Comment by Rask** [comment]
Any idea whether the upcoming Eclipse plugin works with Eclipse forks such as Aptana Studio 3.5+?

**Comment by ncjones** [comment]
It should as long as Aptana is based on the latest version of Eclipse which is what I have been developing against. I'm not yet sure which versions are supported. I'm fairly sure changes will be required to support older versions. You are welcome to help testing this.

**Comment by RichSteele** [comment]
And I'm almost embarrassed to ask but what are the chances to make the
plugin compatible with Kepler?

**Comment by rohitmanglik** [comment]
It's showing "Importing Maven Projects" has encountered a problem. Invalid project description.

**Comment by treyhunner** [comment]
There is an open pull request to add the Eclipse logo to the EditorConfig website: editorconfig/editorconfig.github.com#34.

I'm happy to update the pull request, add the logo, and release the bounty to the creator once the plugin is declared ready.

**Comment by treyhunner** [comment]
@ncjones's :boom:  Eclipse EditorConfig plugin is now listed on the homepage.  Closing this issue.

Thank you to all who wrote code, tested, and helped out with this! :heart:
