### ISSUE TITLE
[Visual Studio] Support domain specific `indent_brace_style`

### ISSUE THREAD

**Issue by zaus** [editorconfig/editorconfig#112]
Per [Ideas for Domain-Specific Properties](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#ideas-for-domain-specific-properties), please consider supporting `indent_brace_style`.

Specific scenario -- I prefer "end of line K&R", but the owner of the code I'm working on prefers "at next line BSD".  I'd like my settings as the default, but when I work on the other specific solution/project to use their settings.

**Comment by Golfenstein3D** [comment]
From the documentation: _"Domain-specific properties are those which may not be meaningful for some file formats."_ Conversely, **they may be meaningful**. Assuming that file format = file extension = language, domain-specific properties are not meant to be agnostic. If an editor is focused on certain languages, domain-specific properties relevant to that editor should be relevant to its EditorConfig extension.

ReSharper isn't free, and only works in Visual Studio. If the EditorConfig plugins for Visual Studio and VS Code both implement `indent_brace_style` that could be very meaningful.

**Comment by Zvirja** [comment]
@jedmao Is there any plays to re-open this issue? That would be the very useful feature, because there are projects that require different brace policies. The @Golfenstein3D remark definitely makes sense.
