### ISSUE TITLE
Gedit 3.8.3 only supports python3 plugins

### ISSUE THREAD

**Issue by swansontec** [editorconfig/editorconfig#121]
I tried installing the editorconfig gedit plugin on my Arch Linux box, only to see the following error:

```
(gedit:5323): libpeas-WARNING **: Could not find loader 'python' for plugin 'editorconfig_gedit'
```

After some deep research, it turns out that the latest version of gedit no longer contains python2 plugin support. Therefore, our options are to either port the plugin to python3 or re-write it in C.

**Comment by flipdazed** [comment]
fixed for latex plugin - http://stackoverflow.com/a/38235346/4013571
