### ISSUE TITLE
Conflict with CodeRush

### ISSUE THREAD

**Issue by jsodeman** [editorconfig/editorconfig#129]
In trying out the EditorConfig Visual Studio extension, I get the following error during VS startup. Disabling EditorConfig fixes the error.

Error:
Could not create DevExpress.CodeRush.VSCore.VsixPluginExtensionService11. Please ensure that the DXCore is installed correctly for this version of Visual Studio.

TargetInvocationException: Exception has been thrown by the target of an invocation.

**Comment by Mpdreamz** [comment]
Closing this because the ticket is nearly 3 years old and @xuhdev never got a reply.

If any CodeRush users still have issues please open a ticket here: https://github.com/editorconfig/editorconfig-visualstudio/issues
