### ISSUE TITLE
insert_final_newline = true is not inserting new line in Notepad++

### ISSUE THREAD

**Issue by johnjd** [editorconfig/editorconfig#149]
I am using editorconfig with Notepad++ 6.5.5 (- on Windows 7).
The .editorconfig file has the configuration 'insert_final_newline = true'. However, the final newline is not getting introduced.
##

**Comment by danilaml** [comment]
Sorry for bumping this but there in the settings of n++ I could find this option?

**Comment by xuhdev** [comment]
Not yet. The reason is that I barely use Windows... If anyone wants to take over the maintainance of this plugin, I'm happy to help.

**Comment by ffes** [comment]
With https://github.com/editorconfig/editorconfig-notepad-plus-plus/pull/7 being merged, this one can be closed.

**Comment by ffes** [comment]
Fixed
