### ISSUE TITLE
Emacs does not apply editorconfig rules to css/scss files

### ISSUE THREAD

**Issue by johnjelinek** [editorconfig/editorconfig#154]
`.editorconfig`:
```
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
chartset = utf-8
trim_trailing_whitespace = true
```

When I open emacs, it still wants to apply 4 spaces to my scss file in the same directory as `.editorconfig`, example:

```
@mixin linear-gradient($fromColor, $toColor) {
    background-image: -webkit-linear-gradient(top, $fromColor, $toColor);
    background-image:    -moz-linear-gradient(top, $fromColor, $toColor);
    background-image:      -o-linear-gradient(top, $fromColor, $toColor);
    background-image:         linear-gradient(top, $fromColor, $toColor);
}
```

**Comment by NdYAG** [comment]
`scss-mode` shares the same indentaion config of `css-mode`, which is `css-indent-offset`.

`(add-to-list 'editorconfig-indentation-alist '(scss-mode css-indent-offset)`

It would be nice to add this as a default config.

**Comment by xuhdev** [comment]
@NdYAG @johnjelinek  Can you confirm it works with the latest emacs plugin?

**Comment by xuhdev** [comment]
I've added scss-mode support editorconfig/editorconfig-emacs@6fcae90cbe88f98ccc6b152f04cc6d2ffaaab288

**Comment by NdYAG** [comment]
It works for me.
https://github.com/antonj/scss-mode/blob/master/scss-mode.el#L87
scss-mode is derived from css-mode, and doesn't change indentation rules.
