### ISSUE TITLE
Feature request: CLI linter

### ISSUE THREAD

**Issue by mcandre** [editorconfig/editorconfig#162]
Could we get a basic command line linter that reports files that don't conform to `.editorconfig`, similar to how JSHint, splint, checkstyle, etc. work? Some developers may wish to add style requirements or reports in their build / CI systems.

**Comment by SethFalco** [comment]
For anyone who runs into this via search engine, a maintained alternative to ECLint is editorconfig-checker.

See:

- https://editorconfig-checker.github.io/
- https://github.com/editorconfig-checker/editorconfig-checker
