### ISSUE TITLE
Errors with Resharper

### ISSUE THREAD

**Issue by freeboarder** [editorconfig/editorconfig#167]
Editor Config obviously tries to read temporary Resharper (8.2) files and generates an error (in the Visual Studio Error pane). For example:

Error	3	EditorConfig core error: Input file must be a full path name.	ReSharper.edea6fee-5c41-4c65-9a7b-cc7250a7aa01	1	1	
Error	4	EditorConfig core error: Input file must be a full path name.	ReSharper.3ed7d7b3-71f3-430e-a1d0-de9e1fd2b98b	1	1	

Probably it would be a good idea to exclude files starting with "Resharper.". It's not obvious to me why Editor Config tries to read these files in the first place. Maybe the source of the error lies here.

**Comment by kawazoe** [comment]
Same for those starting with `StackTraceExplorerEditor` since they are also related to Resharper v10

```EditorConfig core error: Input file must be a full path name. - StackTraceExplorerEditor.Wumicum```

**Comment by Mpdreamz** [comment]
closing this in favor of the editorconfig/editorconfig-visualstudio#33
