### ISSUE TITLE
New property: visual line wrapping.

### ISSUE THREAD

**Issue by cirosantilli** [editorconfig/editorconfig#168]
For programming languages, almost all styles ask programmers to manually add newlines to keep lines under 80 chars, and information is organized by lines, so you usually don't want your editor to wrap the lines which would mungle the logic.

For prose however (markdown, latex, etc.) the situation is much less clear and both styles exist:
- add newlines to keep under 80 characters. You will not want visual wrapping in this case.
- don't add newlines. You will want visual wrapping or else you won't see long lines.

I propose a `visual_wrap` option be added to distinguish between the above cases: if would toggle visual wrapping, not automatically add newlines.

Related request: https://github.com/editorconfig/editorconfig/issues/89

**Comment by PaulDMooney** [comment]
I know this is long closed but it does make some sense. It would be helpful to hint to the editor that for certain file types it should wrap the lines, and for rest don't. For example, usually people don't want wrapping for their code or configuration however displaying wrapping for .md or .txt files can be helpful. I can't imagine who on my team would want to scroll across a 1,000 column one line paragraph that may show up in one of these files. If there happens to be someone out there that does want to do that then it can be overridden at the editor level.

This feature doesn't fall into the EditorConfig mission statement to ensure editors produce files which adhere to defined styles, but at the same time isn't EditorConfig also about being a universal editor configuration? So why can't there be some visual settings for the editor defined here as well? I understand that might be a slippery precedent for requests for visuals that make less sense (like defining font size!), but I'm sure there are some that make good sense.

**Comment by xuhdev** [comment]
@PaulDMooney Thanks for your comments. We currently have [max_line_length](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#max_line_length): this should be good enough for line wrapping, and display a column indicator if supported by the editor. However, I don't see your point that a column indicator is displayed but no line wrapping should be done.

**Comment by PaulDMooney** [comment]
@xuhdev Thanks for the quick response.

The max_line_length is a hard line wrap. There may be cases where we don't want this for certain file types, we don't want end_of_line characters inserted and changing the file for whatever reason (like it could ruin the format another application might be expecting). But we do want a soft line wrap to keep things readable and even responsive to changes in editor width. 

I didn't say anything about a column indicator so I'm not sure what my point was supposed to be with that either :), maybe if I rephrase part of my example to hopefully clear up what I meant:

> I can't imagine who on my team would want to scroll across a 1,000 _character_ one line paragraph that may show up in one of these files. "

**Comment by inf3rno** [comment]
@PaulDMooney  +1, in my current case I cannot soft wrap md files only by Webstorm, because there is only a global option for soft wrapping. All I can do is always clicking on soft wrap by the active editor any time I open an md file. :S :S :S

**Comment by szkrd** [comment]
Exact use case here, like with @inf3rno - soft tab vs hard tab would be so nice to have.

I used jEdit long long ago and there it was possible to set it via the config line (at the end of each file, foro verriding global settings):
```javascript
// :wrap=soft:maxLineLen=80:
```

Possible values for **wrap**: none, soft, hard.
Their docs: http://www.jedit.org/users-guide/word-wrap.html

**Comment by jchook** [comment]
> Even if that were the case, what about the 10% or the 20% who don't have the same preference as you? Fuck them?

@cirosantilli seems like this is a problem with `editorconfig` not the spec. Why can't we have overrides of the .editorconfig file in the directory?

**Comment by jedmao** [comment]
@jchook like what? Can you furnish an example where that would be useful?

**Comment by jchook** [comment]
Sure, look at any language with inheritance. A more specific case commonly has the ability to override the more general cases it inherits (unless prohibited).

In the scenario of editorconfig, the actual configuration of the user's editor instance/process is the most specific case. The `.editorconfig` file is a more general prescription, which could offer it's own inheritance (think `eslint-config-airbnb` except `editorconfig-airbnb`).

It's a simple concept that is virtually ubiquitous in software. The OP is a perfectly "furnished" example.

**Comment by jchook** [comment]
For a more specific rendition of how this might work, say your editor config looks like this...

```
[*]
end_of_line = lf
insert_final_newline = true
visual_wrap = true
```

Now, say you don't like the `visual_wrap`, and it happens to be a "non-enforced" rule, so your "local override" file looks like this:

```
[*]
visual_wrap = false
```

Now everyone is happy.

**Comment by jchook** [comment]
For my exact example, say I have a blog where I write my articles in markdown, and the code in PHP. I strongly dislike soft-wrapped lines in the PHP (would rather scroll to the right, write shorter lines, or hard-wrap lines). For markdown, I want the lines to soft-wrap at 80 chars because I strongly dislike forcing the author to hard-wrap or have 1000 lightyears of rightward scrolling.

I also have multiple contributors and some of them have multiple machines they use to write either or both PHP + Markdown.

Would be fantastic if my `.editorconfig` could say something similar to:

```
[*]
preferred_line_length = 80
soft_wrap = false

[*.md]
soft_wrap = true
```

This way whenever a new contributor clones the codebase, their editor is automatically working like mine and I can expect them to not use manual hard-wrapping or similar without having to write instructions for each editor app.

And separately, it would be cool if each contributor could override "non-enforced" rules for their local machine, perhaps in their dotfiles, e.g. `~/.editorconfigrc` or similar, or a file that is `.gitignore`'d.

**Comment by jedmao** [comment]
@jchook I think what you want can be achieved through [language-specific editor settings like in vscode](https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings). For example, this does exactly what you want here:
```json
{
    "[markdown]": {
        "editor.wordWrap": "wordWrapColumn",
        "editor.wordWrapColumn": 80
    }
}
```
I'm not sure about other editors, but to me, this validates that this particular issue should not be handled by EditorConfig, as it steps into user preference territory, but *should* be handled by editors. If the feature doesn't exist in the editor of your choice, perhaps submit the feature request there?

**Comment by jchook** [comment]
@jedmao thanks for the snippet!

**Comment by jchook** [comment]
Based on the discussion here it seems "EditorConfig" would be more appropriately named "CodeConformity". To me, supporting preferential settings with local overrides seems like a completely reasonable and useful feature.

**Comment by jedmao** [comment]
Water under the bridge 😃

**Comment by yan12125** [comment]
For those who use vim/neovim, the following function adds a custom property `visual_wrap`:
```vim
" Implements https://github.com/editorconfig/editorconfig/issues/168
" Inspired by https://github.com/editorconfig/editorconfig/issues/190#issuecomment-520423166
function! EditorConfigHook(config)
    if has_key(a:config, 'visual_wrap')
        if a:config['visual_wrap'] == 'true'
            set wrap
        endif
    endif

    return 0   " Return 0 to show no error happened
endfunction

call editorconfig#AddNewHook(function('EditorConfigHook'))
```

**Comment by po1xi548Rysh8BH6** [comment]
This is obviously an old issue but I would like to suggest the same. visual_wrap would be a great addition when working on LaTeX files and I would also certainly expect that to be a project-wide setting that all contributors would benefit from.
