### ISSUE TITLE
UI-Blocking when opening large files

### ISSUE THREAD

**Issue by Manuel-S** [editorconfig/editorconfig#171]
Hi,
when opening large files using the visual studio extension, the UI blocks for minutes while displaying "EditorConfig is cleaning [..]".

I guess this is caused by the "TrimTrailingWhitespaces" option. Is it possible to do this transformation in a background thread and also support cancellation (by closing the file)?

**Comment by Mpdreamz** [comment]
This is now fixed in `master` of the visual studio plugin:

https://github.com/editorconfig/editorconfig-visualstudio/pull/42

The performance on large files is much much better and I have not experienced bocking behaviour.
