### ISSUE TITLE
Visual Studio extension description not clear what it does after creating .editorconfig

### ISSUE THREAD

**Issue by KindDragon** [editorconfig/editorconfig#174]
Visual Studio extension description not clear what it does after creating .editorconfig

http://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328

**Comment by ite-klass** [comment]
The description is especially not clear enough in where it applies these settings.
Will they be set in the langauge specific "Tabs" configuration?
If so, that only works for C# with `[*.cs]` for me, but not for js, css or less.
If on the other hand it will not use the VS Tabs settings, but instead influence the text editor according to opened files directly, then I’m confused why the Tabs setting for C# does get changed.

**Comment by ite-klass** [comment]
From https://github.com/editorconfig/editorconfig/issues/181#issuecomment-61487480

> You shouldn't expect to see settings from your .editorconfig file's configuration in the text editor options. Those are your global settings. The way the plugin works is it loads your editorconfig settings for every file (tab) you switch to and then restores your global settings when you lose focus from that file.

This information should be put on the plugin store page and the README.

**Comment by ite-klass** [comment]
Contrary to that description, after I opened a matching file the setting does change and I can see it in the text editor settings, and after closing the file I still see that tab configuration. So there is no restoration on losing focus as described.

I’m using VS2013 and ReSharper plugin.

**Comment by jedmao** [comment]
@ite-klass I think you're right. I verified this earlier that the settings are not being restored properly. They were designed to do this, originally, but somehow that code was lost or replaced.

**Comment by jedmao** [comment]
@ite-klass see https://github.com/editorconfig/editorconfig-visualstudio/issues/18

**Comment by Mpdreamz** [comment]
I've updated the readme and will update the gallery once we release the next version
