### ISSUE TITLE
[VS] Add new template

### ISSUE THREAD

**Issue by jerone** [editorconfig/editorconfig#175]
Right now I have to manually add an `.editorconfig` file for every project (and subfolders when needed).

It would be nice if an EditorConfig template file was available in the "Add New Item" window (see context menu "Add" > "New Item") for Visual Studio.

**Comment by Mpdreamz** [comment]
This is now implemented in the `master` branch of the plugin:

https://github.com/editorconfig/editorconfig-visualstudio/pull/22
