### ISSUE TITLE
Automatic Linter Configuration?

### ISSUE THREAD

**Issue by andrewdeandrade** [editorconfig/editorconfig#183]
Are there any plans for performing automatic linter configuration in future versions of .editorconfig.

It would be really nice to be able to define on a filetype-by-filetype basis what linters are enabled and disabled and the paths to the `.rc` and `.ignore` files for each linter. Automatic setup of syntastic, SublimeLinter and flycheck would be most awesome.
##

**Comment by matrixise** [comment]
Hi,
any news about this issue ?

thank you

**Comment by xuhdev** [comment]
@matrixise I don't have time to work on [this project](https://github.com/xuhdev/editorconfig-cf) alone, but I have already written a contribution guideline. Feel free to contribute to the part that is relevant to your own language (I'm not know-all-languages person...).

**Comment by cxw42** [comment]
Can this be closed as a duplicate of #103?

**Comment by xuhdev** [comment]
> Can this be closed as a duplicate of #103?

I believe so. Closing now.
