### ISSUE TITLE
Provide mechanism to turn off editorconfig for some files

### ISSUE THREAD

**Issue by tmccombs** [editorconfig/editorconfig#187]
It would be nice if there was a mechanism to turn off editorconfig all together for a certain class of files.

My motiviation for requesting this feature is that when I have editorconfig setup for Emacs, the normal behaviour of SLIME while editing lisp files is messed up. Specifically, it doesn't correctly align continued lines.  Since lisp indentation depends on the form being used, editorconfig is two simple to work correctly. I would like to have some option to, say, turn off editorconfig for all lisp files.

**Comment by rayshan** [comment]
So is the recommended way of doing this just resetting everything to `none`? Use case: use editorconfig on all files except `package.json` files, because npm CLI resets whitespaces anyways.

**Comment by jedmao** [comment]
@rayshan I usually have a config at root that looks something like this to handle package.json files:

```ini
root = true

[*]
indent_style = tab
end_of_line = lf
trim_trailing_whitespace = true
insert_final_newline = true

[package.json]
indent_style = space
indent_size = 2
```

The npm CLI does reset whitespace; however, there are many times I edit package.json files manually, like to add/remove scripts and such.

**Comment by rayshan** [comment]
Thanks @jedmao

**Comment by xuhdev** [comment]
Closing this issue
