### ISSUE TITLE
EditorConfig Emacs Question

### ISSUE THREAD

**Issue by pantocrator27** [editorconfig/editorconfig#193]
Your instructions for Emacs indicates how to install the editorconfig.el file in one's local home directory.  How could I install it for the benefit of all user's of a machine?

Thanks in advance!

~Marshall

**Comment by xuhdev** [comment]
You can drop it in a system elisp directory (it's `/usr/share/emacs/site-lisp` on my machine).

**Comment by pantocrator27** [comment]
Thanks!  I hate to ask, but I have tried installing the plugin both ways and still am unable to get it to work for me in Emacs.  I am currently running Ubuntu 14.04 with Emacs 24.3.1.  I installed these and editorconfig-core using apt-get.  Any help would be greatly appreciated.  I am kinda stuck at this point.

**Comment by xuhdev** [comment]
OK, can you tell me what makes you think it does not work? It may not be an installation issue..

**Comment by pantocrator27** [comment]
I have the following `.editorconfig` file in the root of my project:

```
root = true

[*]
end_of_line = lf
insert_final_newline = true
charset = utf-8
indent_style = space
indent_size = 4
max_line_length = 80
```

In Emacs, in the root of my project, I can open a file called `test-editorconfig`.

I can start typing sentences and go beyond the `max_line_length` of 80. Then on new lines, I can tab and the tab stops are in multiples of 8.

**Comment by xuhdev** [comment]
Everything seems fine. Can you try to run `editorconfig /path/to/a/file/in/project` on the terminal can paste the output here?

**Comment by pantocrator27** [comment]
Sorry for my delay.  I don't see if my example above how everything seemed fine since I had `indent_style = space` and `index_size = 4` but emacs was injecting tabs and not spaces.  I had confirmed this by performing a grep of the file after the fact for the presense of tabs.  Here is the result of running an `editorconfig` command against a file.

```
end_of_line=lf
insert_final_newline=true
charset=utf-8
indent_style=space
indent_size=4
max_line_length=80
tab_width=3
```

**Comment by xuhdev** [comment]
Sorry for the confusion, I mean what you have done makes sense, but the effect we see. From the output, the editorconfig core is also working properly.

Can you try to install the version in [marmalade](https://marmalade-repo.org/packages)? You can install from inside Emacs by running `package-install`. Or you can try to install with [el-get](https://github.com/dimitri/el-get).

**Comment by jdivock** [comment]
I'm seeing something similar. I've installed editorconfig via the package installer and pulled it from melpa. It's installed and loaded, yet not doing anything. My editorconfig is file and configuration is fine as my settings work under vim, it just appears the emacs plugin isn't having any affect on my environment.

Here's my editorconfig 

```
# editorconfig.org
root = true

[*]
indent_style = space
indent_size = 8
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.css, *.less, *.scss]
indent_style = space
intent_size = 2
```

but here's what my js-mode and css indent settings show

```
css-indent-offset is a variable defined in `css-mode.el'.
Its value is 4
```

```
js-indent-level is a variable defined in `js.el'.
Its value is 4

  This variable is safe as a file local variable if its value
  satisfies the predicate `integerp'.
```

and I'm certain the editorconfig plugin is loaded as it shows up when I check

```
package-activated-list is a variable defined in `package.el'.
Its value is
(ac-js2 skewer-mode js2-mode ... editorconfig ....)
```

I don't see any errors in messages, just that editorconfig has been loaded.

**Comment by gizmomogwai** [comment]
for me emacs did not find the editorconfig executable.
could you execute this in your *scratch* buffer and show us the output.

    (executable-find edconf-exec-path)

the plugin just does nothing if it does not find the executable.

**Comment by pantocrator27** [comment]
i was able to fix the issue through a combination of compiling editorconfig from scratch and upgrading emacs.
