### ISSUE TITLE
Xcode plugin? [$30]

### ISSUE THREAD

**Issue by rayshan** [editorconfig/editorconfig#194]
Hi, how can we make Xcode support and respect `.editorconfig`?

**Comment by xuhdev** [comment]
There is no way yet. Contribution is welcome.

**Comment by treyhunner** [comment]
:+1: An Xcode plugin would be very welcome

**Comment by treyhunner** [comment]
I just added a bounty for this on Bountysource.

The requirements for meeting this bounty are similar to those of the past bountied plugins.

Plugin should at least support:

- `indent_style`
- `indent_size`
- `tab_width` (if possible)

And preferably support:

- `trim_trailing_whitespace`
- `insert_final_newline`
- `end_of_line`
- `charset`

**Comment by MarcoSero** [comment]
I have implemented the plugin. I will release and open source it shortly :dizzy:

**Comment by MarcoSero** [comment]
The plugin is here https://github.com/MarcoSero/EditorConfig-Xcode
It will soon be available on Alcatraz https://github.com/supermarin/alcatraz-packages/pull/319

**Comment by treyhunner** [comment]
Thanks @MarcoSero!

You might want to list supported options/behavior in the README file. Which options are supported right now?

**Comment by MarcoSero** [comment]
@treyhunner see my comment :point_up: 
I'll add the supported options to the README and I'm planning on adding more features.

**Comment by allejo** [comment]
:+1:

**Comment by treyhunner** [comment]
I opened a pull request to add a link to this plugin on the website (editorconfig/editorconfig.github.com#46).

**Comment by treyhunner** [comment]
The Xcode plugin is currently listed on the homepage.  I am closing this issue as resolved. @MarcoSero if you want to claim the $30 bounty, I think you'll need to sign up for Bountysource.

Thanks again @MarcoSero!

**Comment by MarcoSero** [comment]
:dizzy:

**Comment by rayshan** [comment]
Thanks guys!

**Comment by codytwinton** [comment]
Xcode 8 has removed Plugins in favor of extensions. Any plans to port over to an Extension @MarcoSero ?

**Comment by MarcoSero** [comment]
No, at the moment I have no plans to port it over I'm afraid.
