### ISSUE TITLE
Problems with files on network drives

### ISSUE THREAD

**Issue by sindresorhus** [editorconfig/editorconfig#195]
https://github.com/sindresorhus/atom-editorconfig/issues/28

// @treyhunner @jedmao @RReverser

-

Sidenote: Annoying that issue trackers are not enabled on the individual repos. There's not even a link to this issue tracker. @treyhunner Can you please reconsider? This makes it a lot harder for people to report issues in a relevant matter.

**Comment by jerone** [comment]
After a lot of `console.log`'s I've found out that the code bugs on https://github.com/editorconfig/editorconfig-core-js/blob/master/editorconfig.js#L69 where `path.resolve(filepath).match(/^[^\\]+\\/)` resulting in `null`, making `[0]` not possible.

**Comment by jerone** [comment]
Probably related to https://github.com/editorconfig/editorconfig-core-js/pull/12

**Comment by jerone** [comment]
Hoping someone would take this issue, still having problems with `atom 0.179.0`. I identified the problem, see https://github.com/editorconfig/editorconfig/issues/195#issuecomment-70824543, but have no idea how to fix it.

**Comment by awayken** [comment]
:frowning: I'm having this issue, too.

**Comment by treyhunner** [comment]
I'm trying to reproduce this problem.  Is this Windows-specific?  Is anyone currently experiencing this problem on Linux/Mac?

**Comment by treyhunner** [comment]
I'm guessing the problem is in [getConfigFileNames](https://github.com/editorconfig/editorconfig-core-js/blob/master/editorconfig.js#L29) or [getFilepathRoot](https://github.com/editorconfig/editorconfig-core-js/blob/master/editorconfig.js#L67).

**Comment by jerone** [comment]
@treyhunner commented on [12 mrt. 2015 22:16 CET](https://github.com/editorconfig/editorconfig/issues/195#issuecomment-78621315 "2015-03-12T21:16:52Z - Replied by Github Comment Enhancer"):
> I'm guessing the problem is in [getConfigFileNames](https://github.com/editorconfig/editorconfig-core-js/blob/master/editorconfig.js#L29) or [getFilepathRoot](https://github.com/editorconfig/editorconfig-core-js/blob/master/editorconfig.js#L67).

See https://github.com/editorconfig/editorconfig/issues/195#issuecomment-70824543

**Comment by treyhunner** [comment]
This was changed in 94f8ce73e89d0a8021d35eee32ab98a741ea07c5.

It seems like

    path.resolve(filepath).match(/^[^\\]+\\/)

Should be

    path.resolve(filepath).match(/^.+\\/)

@jedmao do you remember why you made that `[^\\]+\\`?

**Comment by jedmao** [comment]
@treyhunner it took some research, but yeah. It was in response to @xuhdev's concern in [this comment](https://github.com/editorconfig/editorconfig-core-js/pull/12#issuecomment-64156400).

**Comment by macro1** [comment]
Or `/^(\\\\)?[^\\]+\\/`. It's greedy so it includes as much of the path as possible.

**Comment by macro1** [comment]
Actually... Can we use this?
https://nodejs.org/api/path.html#path_path_parse_pathstring

**Comment by macro1** [comment]
Confirmed the fix I have in PR works with Node.js v0.10.9 with the Atom plugin.

**Comment by treyhunner** [comment]
@macro1 :sparkling_heart: thank you!

**Comment by awayken** [comment]
Huzzah!

A :trophy: for everyone who helped fix this issue!
