### ISSUE TITLE
Vim plugin formatting failure

### ISSUE THREAD

**Issue by LukeMauldin** [editorconfig/editorconfig#200]
When using the editorconfig plugin along with the vim fugitive plugin, I get this failure when using fugitive to navigate Git commit history:
Failed to execute "editorconfig 'fugitive:///Users/lmauldin/dev/pe/apps/pmtool/peo/pms420/engine/.git//454dd19481199bfba1c788db9f4896a4a8adb8be'". Exit code: 1
Message:
['Input file must be a full path name.']

**Comment by xuhdev** [comment]
I add a `g:EditorConfig_execlude_patterns` option 996a00b12badd4bfdaddde73991490455e35cdee

You should be able to ignore fugitive buffers with `let g:EditorConfig_exclude_patterns = ['fugitive://.*']`

**Comment by LukeMauldin** [comment]
That works well, thank you
