### ISSUE TITLE
Emacs package suggestions

### ISSUE THREAD

**Issue by Silex** [editorconfig/editorconfig#202]
Hello,

Since I can't create issues on the emacs package repo (https://github.com/editorconfig/editorconfig-emacs), I create it here.

There are several things that should be improved:
- It should really be a global minor mode instead of inconditionally adding itself to `find-file-hook` (https://github.com/editorconfig/editorconfig-emacs/blob/master/editorconfig.el#L297). Packages that alter global state by simply requiring them are bad.
- It forces me to use `.editorconfig` files. I'd like to specify a global config for all my projects reguarding of where they are stored, e.g a "default config". Ideally something with some customizable variable like:

``` elisp
(setq editorconfig-defaults '(("*" :end_of_line 'lf :indent_size 2)
                              ("*.py" :indent_style 'space :indent_size 4)))
```
##

**Comment by xuhdev** [comment]
> Since I can't create issues on the emacs package repo (https://github.com/editorconfig/editorconfig-emacs), I create it here.
>
You are in the right place to report issues. The issues are supposed to
be reported here.

> There are several things that should be improved:
>
> * It should really be a global minor mode instead of inconditionally adding itself to `find-file-hook` (https://github.com/editorconfig/editorconfig-emacs/blob/master/editorconfig.el#L297). Packages that alter global state by simply requiring them are bad.

I agree with this. I remembered there was an argument that which way
should we go, but I cannot find the link. Probably I'll go this way
eventually.

> * It forces me to use `.editorconfig` files. I'd like to specify a global config for all my projects reguarding of where they are stored, e.g a "default config". Something with some customizable variable like `(setq editorconfig-defaults '(("*" :end_of_line 'lf :indent_size 2) ("*.py" :indent_style 'space :indent_size 4)))`

If you want to use it in a project where EditorConfig is not used, you
can create a `~/.editorconfig` file.

Let me know if you have any other questions.

**Comment by Silex** [comment]
>> * It forces me to use `.editorconfig` files. I'd like to specify a global config for all my projects reguarding of where they are stored, e.g a "default config". Something with some customizable variable like `(setq editorconfig-defaults '(("*" :end_of_line 'lf :indent_size 2) ("*.py" :indent_style 'space :indent_size 4)))`

> If you want to use it in a project where EditorConfig is not used, you
> can create a `~/.editorconfig` file.

I doubt this will work over TRAMP, except if editor-config specifically checks for `~` if nothing was found.

**Comment by xuhdev** [comment]
@Silex EditorConfig always check all `.editorconfig` files from the current directory up to root directory, which means, if there is no project `.editorconfig` file specifying `root = true`, the one under home directory is always effective if the project is in any subdirectory of your home. This also allows you to specify multiple `.editorconfig` files in different directories in a project.

**Comment by xuhdev** [comment]
Can this issue be closed now? editorconfig now acts as a minor mode.

**Comment by Silex** [comment]
Alright.
