### ISSUE TITLE
Question: hooks in vim allow me to change other related settings?

### ISSUE THREAD

**Issue by jasonkarns** [editorconfig/editorconfig#203]
According to the docs, there are some additional hooks in editorconfig-vim.

What I would like to do is configure a hook in my vimrc that is invoked when an editorconfig is 'active'. Mainly, if editorconfig is active, and `indent_style = tab` I want to remove the tab char from `listchars`. Conversely, if `indent_style = space`, I want to ensure the tab char is included in `listchars`.

The end goal is to make leading tab-chars invisible iff indent_style is tab and make them visible otherwise.

(And I'm new to vimscript so this is a stretch for me.)

**Comment by xuhdev** [comment]
@jasonkarns Do you still need help with the script? I can write one if you still need it :)

**Comment by jasonkarns** [comment]
Yeah, I'd appreciate it!

**Comment by xuhdev** [comment]
Please try the following code:

```vim
function! ListCharHook(config)
    if !has_key(a:config, 'indent_style')
        return 0
    endif
    
    if a:config['indent_style'] == 'tab'
        setl listchars-=tab:<>
    elseif a:config['indent_style'] == 'space'
        setl listchars+=tab:<>
    endif

    return 0   " Return 0 to show no error happened
endfunction

call editorconfig#AddNewHook(function('ListCharHook'))
```

**Comment by jasonkarns** [comment]
thanks
