### ISSUE TITLE
Ability to turn off rules off for specific file patterns

### ISSUE THREAD

**Issue by mcandre** [editorconfig/editorconfig#205]
As a power user, I want to be able to turn rules on for most (`[*]`) files, but turn them back off for certain files. Could we add a `disabled` keyword?

For example, if I want most files to be 80-char width, but let XML files be infinitely long, I could write:

```
[*]
max_line_length = 80

[*.xml]
max_line_length = disabled
```

As a workaround, I can write `max_line_length = 1000000`, but this pattern wouldn't work qualitative rules.

**Comment by jedmao** [comment]
It already works exactly how you describe. You could use `disabled`, `none`, `auto` or `foo` and it would do the same thing.
