### ISSUE TITLE
Copy & paste from other file with different line ending

### ISSUE THREAD

**Issue by matiasbeckerle** [editorconfig/editorconfig#213]
I'm using Visual Studio 2013 community edition with the EditorConfig plugin on Windows 8.1. For an unknown reason it doesn't seems to work when I paste some code from a file with another line ending (and in another project).

Example:

My solution has an `.editorconfig` file with linux line ending. If I paste some code from a file with windows line ending then my file gets corrupted with mixed line endings.

I'm the only one with this issue? Maybe I did something wrong?

**Comment by jedmao** [comment]
It's been [mentioned before too](https://github.com/editorconfig/editorconfig/issues/77#issuecomment-12759515), but this issue should be submitted on [the appropriate issue tracker here](https://github.com/editorconfig/editorconfig-visualstudio). I can't find it now, but I vaguely remember someone saying Microsoft overrides the ability to do this.

**Comment by jedmao** [comment]
Ah yes, it was mentioned [here](https://github.com/editorconfig/editorconfig-visualstudio/pull/15#issuecomment-67247562).

**Comment by matiasbeckerle** [comment]
Well, I want to mention a few things @jedmao:

1. Thanks for answering so quickly.
2. I didn't know about the issue tracker for Visual Studio plugin, sorry for that.
3. I couldn't find another related issue, that's why I created this one. Thanks for let me know about the other one. I hope will merged soon!
4. I'm closing this one because is in the wrong place and there is already a [PR to fix it](https://github.com/editorconfig/editorconfig-visualstudio/pull/15).
