### ISSUE TITLE
Introduce a [{Makefile,*.mk}] section on the editorconfig.org homepage

### ISSUE THREAD

**Issue by timdream** [editorconfig/editorconfig#216]
The current example on home page blindly rewrites Makefile indents into spaces. I made me impossible to edit Makefile in Sublime Text 2 with the linked plug-in. Not sure if happens on other plug-ins too but I would recommend amending the example on home page like mozilla-b2g/gaia#29582.

ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1155979

**Comment by xuhdev** [comment]
:+1:
