### ISSUE TITLE
Not working on Visual Studio 2013

### ISSUE THREAD

**Issue by dliuzzi** [editorconfig/editorconfig#217]
Given the following configuration file:

**.editorconfig**

```ini
root = true

[*]
indent_size = 2
indent_style = space
insert_final_newline = true
trim_trailing_whitespace = true
```

And the following sample file (deliberately unformatted):

**sample.html** (original)

```html
<!DOCTYPE html>
<html>
<head>
<title>Lorem ipsum</title>
</head>
<body>
<p>Lorem ipsum dolor sit amet.</p>
</body>
</html>
```

When I open this file in Visual Studio 2013 and do *Edit > Advanced > Format Document* (<kbd>Ctrl</kbd>+<kbd>E</kbd>, <kbd>D</kbd>), the document is indented to four spaces, seemingly ignoring the `.editorconfig` file:

**sample.html** (Visual Studio 2013)

```html
<!DOCTYPE html>
<html>
<head>
    <title>Lorem ipsum</title>
</head>
<body>
    <p>Lorem ipsum dolor sit amet.</p>
</body>
</html>
```

On the other hand, when I do the *same thing* in Visual Studio 2012, the document is indented properly:

**sample.html** (Visual Studio 2012)

```html
<!DOCTYPE html>
<html>
<head>
  <title>Lorem ipsum</title>
</head>
<body>
  <p>Lorem ipsum dolor sit amet.</p>
</body>
</html>
```

---

If it matters, this is the version of Visual Studio 2013 I use:

> Microsoft Visual Studio Community 2013
> Version 12.0.31101.00 Update 4

And this is Visual Studio 2012:

> Microsoft Visual Studio Professional 2012
> Version 11.0.61030.00 Update 4

I'm running **EditorConfig 0.5.0** on both.

**Note that this might be related to GH-191, though I am not 100% sure.**

**Comment by jedmao** [comment]
Please move this issue over to https://github.com/editorconfig/editorconfig-visualstudio/issues. Thanks!
