### ISSUE TITLE
Vim weird behaviour.

### ISSUE THREAD

**Issue by carlitux** [editorconfig/editorconfig#218]
Hey guys,

I don't know if I am doing something wrong. I am usind editorconfig and is working good with python but for coffee, html, css, scss is not working... all setup is in same config file.

**Comment by xuhdev** [comment]
Can you post your configuration file here?

**Comment by carlitux** [comment]
```
# http://editorconfig.org

root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.{py,rst,ini}]
indent_style = space
indent_size = 4

[*.yml]
indent_style = space
indent_size = 2

[*.{coffee,js,css,html,scss}]
ident_style = space
ident_size = 2
```

**Comment by xuhdev** [comment]
@carlitux Sorry for the delay. In your last section, you mistyped `indent_style` -- what you typed was `ident_style`. So does `indent_size`.

**Comment by carlitux** [comment]
@xuhdev Thank you, sorry I had to read carefully.
