### ISSUE TITLE
Create Core library for Emacs Lisp

### ISSUE THREAD

**Issue by treyhunner** [editorconfig/editorconfig#219]
The Emacs plugin is the only one which cannot bundle an EditorConfig library by default.  It might be overkill to create a core library *just* for this plugin, but if anyone is up for the task I think it would be great.

**Comment by xuhdev** [comment]
[This](https://github.com/10sr/editorconfig-core-emacslisp) should solve the problem. Shall we close this issue now?

**Comment by 10sr** [comment]
I will be glad if you try it and give me feedback :smiley_cat:

**Comment by xuhdev** [comment]
@treyhunner I think it would be great if we can incorporate @10sr 's work into the Emacs plugin. Shall we do it?

**Comment by treyhunner** [comment]
@xuhdev sure! I don't want to be the one to do the work but I'm happy to chime in with feedback :smile:

@10sr great work on that library! :+1:

**Comment by 10sr** [comment]
https://github.com/editorconfig/editorconfig-emacs/pull/46
