### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by treyhunner** [editorconfig/editorconfig#221]
Interactions have remained largely civil up to this point.  I think it's time we explicitly stated what we've already been doing implicitly and clarified the manner by which we expect contributors to conduct themselves.

Let's adopted a code of conduct.

I would expect this code of conduct to apply to the mailing list, IRC channel, and documentation/code/issue trackers for all libraries, plugins, and other repos managed within the `editorconfig` organization.

Some codes I've looked at:

- [Citizen Code of Conduct][citizen]
- [Contributor Covenant][covenant] (versions used by [Angular][], [RVM][], and [other projects][covenant projects])
- [Django Code of Conduct][django] (linked to [from here][django link])
- [Ember.js Code of Conduct][ember] (linked to [from here][ember link])
- [Rust Code of Conduct][rust] (some verbage borrowed by [io.js][io.js])

I love how explicit the Django and Ember codes of conduct are, but I also like the brevity of the Contributor Covenant.

The Rust code of conduct lists explicit moderation policies, whereas the Django code of conduct links to [a separate document][django reporting] detailing information about how violations will be handled.

I'm leaning toward recommending the **[Contributor Covenant][covenant]**.

Thoughts?

[angular]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-code-of-conduct
[citizen]: http://citizencodeofconduct.org/
[covenant]: http://contributor-covenant.org/
[covenant projects]: https://github.com/CoralineAda/contributor_covenant#examples-of-projects-using-the-contributor-covenant
[django]: https://www.djangoproject.com/conduct/
[django link]: https://github.com/django/django/blob/master/CONTRIBUTING.rst#code-of-conduct
[django reporting]: https://www.djangoproject.com/conduct/reporting/
[ember]: http://emberjs.com/guidelines/
[ember link]: https://github.com/emberjs/ember.js/blob/master/CODE_OF_CONDUCT.md
[io.js]: https://github.com/nodejs/io.js/blob/master/CONTRIBUTING.md#code-of-conduct
[rust]: http://www.rust-lang.org/conduct.html
[rvm]: https://github.com/rvm/rvm/blob/master/CODE_OF_CONDUCT.md

**Comment by xuhdev** [comment]
Do you have any specific reasons to recommend Contributor Covenant? It looks like the simplest one among all of the five, but it seems that it lacks many details compared to the others (e.g. how violations be handled as you pointed out, IRC nickname rules, etc).

**Comment by xuhdev** [comment]
We would also probably need an IRC logger, otherwise the evidence of any violation would be gone.

**Comment by treyhunner** [comment]
I only recommend it because it seems to contain the core point and the spirit of what we want, leaving us to deal with specifics as they occur.

As for an IRC logger, I do have my own logs for it but no one has used it in many months so I'm not concerned about that right now.

**Comment by xuhdev** [comment]
If we want to be more flexible, I would agree to use contributor covenant.

**Comment by xuhdev** [comment]
Can we close this issue now?

**Comment by treyhunner** [comment]
Yes
