### ISSUE TITLE
vim plugin operates on files outside of repo

### ISSUE THREAD

**Issue by staticshock** [editorconfig/editorconfig#229]
If I'm in a directory with an .editorconfig file that defines, for instance, CRLF newlines, and I open `vim /path/outside/repo`, the plugin saves that file with CRLF newlines.

**Comment by xuhdev** [comment]
I cannot reproduce this with either `autochdir` on or off. Which OS are you on? Can you post the vimrc (or send it privately to me)? Thanks!

**Comment by staticshock** [comment]
My bad, I can't repro it either. Could have been user error.
