### ISSUE TITLE
EditorConfig plugin for PhpStorm breaks line-ending behavior

### ISSUE THREAD

**Issue by ewbarnard** [editorconfig/editorconfig#230]
Original ticket: https://youtrack.jetbrains.com/issue/WI-28482.

The PhpStorm editor has settings for stripping trailing spaces from (all lines, modified lines, never) upon saving a file. With the EditorConfig plugin active, ALL trailing space is stripped from ALL lines unconditionally. It's possible that this is due to an EditorConfig settings/configuration file; I don't know.

EDIT: The issue comes from CakePHP 2.x installing a .editorconfig file containing "trim_trailing_whitespace = true". Not a bug.
##

**Comment by xuhdev** [comment]
Looks fixed now.
