### ISSUE TITLE
Doesn't reset to defaults when switching to a project with no .editorconfig

### ISSUE THREAD

**Issue by JRosanowski** [editorconfig/editorconfig#233]
*** Actually I've copied this issue to editorconfig-visualstudio so this code possibly just be closed ***

Newbie here. I'm not sure if this is a bug or to be expected. I'm using the latest version 0.5.0 with VS2015.

I set up a .editorconfig file like this for a cpp project. My default setting is 2 spaces for indents.

root = true
# 
[*]
indent_style = space
indent_size = 4

So I open the project with the .editorconfig and it changes the indent to 4. Now I switch back to the other project using open recent and the indent size is still 4 spaces. I was expecting it to switch back to an indent size of 2. Anyone have any insight? Thanks.

**Comment by xuhdev** [comment]
As you have reposted the bug to the Visual Studio plugin issue tracker, I'm closing this one
