### ISSUE TITLE
Q: Should trim_trailing_whitespace remove extra newlines at the end of a file?

### ISSUE THREAD

**Issue by rolodato** [editorconfig/editorconfig#234]
I was doing this in vim without editorconfig, but once I switched I noticed that extra newlines aren't being removed. Is this the expected behavior? Haven't managed to find a precise definition as to what this option should do. Thanks!

**Comment by jedmao** [comment]
It's not the expected behavior for `trim_trailing_whitespace`, but it is the expected behavior for `insert_final_newline = false`. What does your `.editorconfig` file look like?

See http://editorconfig.org/#supported-properties:
> trim_trailing_whitespace: set to “true” to remove any whitespace characters preceding newline characters and “false” to ensure it doesn't.

> insert_final_newline: set to “true” ensure file ends with a newline when saving and “false” to ensure it doesn't.

See also:
- https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#trim_trailing_whitespace
- https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#insert_final_newline

**Comment by rolodato** [comment]
I'm using both, this is my .editorconfig so far:

```ini
root = true

[*]
indent_size = 2
indent_style = space
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

I wanted to have files end with one newline, but if there is more than 1 newline at the end of a file it should be stripped. Seems like this combination isn't supported yet?

**Comment by xuhdev** [comment]
@rolodato trim_trailing_whitespace would not delete blank lines. Did you type the extra new lines before manually or editorconfig generates them?

**Comment by rolodato** [comment]
@xuhdev Yes, those lines were added manually (accidentally, which is why I'd like to delete them). Basically I'd like `foo\n\n\n` to become `foo\n` automatically.

**Comment by xuhdev** [comment]
@rolodato Sorry, unfortunately it is currently not supposed to trim blank lines at the end of the files.

**Comment by xuhdev** [comment]
@rolodato However you can add your own options. See `:h editorconfig-hook` for details.

**Comment by rolodato** [comment]
Excellent, thanks for the clarification. I'll look into the hooks for now. In the meantime, would this repo be the correct place to make a feature request?

**Comment by xuhdev** [comment]
@rolodato In your case, it's this repo

**Comment by rolodato** [comment]
@xuhdev Thanks, closing this issue then.
