### ISSUE TITLE
Tripple undo in Coda if trim_trailing_whitespace and insert_final_newline is true

### ISSUE THREAD

**Issue by treiber** [editorconfig/editorconfig#237]
So, I stumbled upon an annoying issue with Coda and the Undo action.
If trim_trailing_whitespace and insert_final_newline is set to true, I have to undo three times until my actual input gets undone. It's twice if only one of the two is true, respectively. I understand the issue, Coda first undoes the final newline action, on next undo the trailing whitespace action and only then my last manual input. Is this standard behavior or is there any way around that - I find it to be super annoying...

Best,
Nik

**Comment by xuhdev** [comment]
@treiber Sorry that the coda plugin is not maintained by us, you need to report the bug to PANIC.

**Comment by treiber** [comment]
Alright, I will. This is not expected behavior though, is it?

**Comment by xuhdev** [comment]
@treiber This part is left to be decided by the plugin. However, I doubt how they can improve it because directly undoing your action before the trimming may be conflicting with what's left after the trimming...

**Comment by treiber** [comment]
[Here's the conversation I had with the developer.](https://twitter.com/willco007/status/660304507788591104)

**Comment by xuhdev** [comment]
Thanks for the update!
