### ISSUE TITLE
Outreach request: Atom editor

### ISSUE THREAD

**Issue by fulldecent** [editorconfig/editorconfig#241]
Would like this to work on Atom

**Comment by jedmao** [comment]
Have you tried [Visual Studio Code](https://code.visualstudio.com/?wt.mc_id=DX_23054&utm_source=Paid+Demand&utm_medium=SEM&utm_content=Bing&utm_campaign=Active+Dev+VS)? It's [Atom-based](http://thenextweb.com/apps/2015/04/30/microsofts-cross-platform-visual-studio-code-app-is-based-on-githubs-atom-editor/) and [has an EditorConfig plugin](https://github.com/Microsoft/vscode-editorconfig).

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/atom-editorconfig

**Comment by fulldecent** [comment]
@sindresorhus Excellent, thank you, I believe this resolves the issue
