### ISSUE TITLE
Outreach request: Validation

### ISSUE THREAD

**Issue by fulldecent** [editorconfig/editorconfig#242]
If it's a standard, it should be validated.

Requesting a validator and Travis CI setup instructions.

**Comment by treyhunner** [comment]
:+1: I would also like to see validators.

It's a non-trivial problem, but not an impossible one. Indentation will probably need to be handled on a case-by-case basis for each programming language.

**Comment by jedmao** [comment]
@denis-sokolov [made a comment](https://github.com/jedmao/eclint/pull/36#issuecomment-157652359) about [`lintspaces`](https://www.npmjs.com/package/lintspaces), which uses [ignore patterns](https://github.com/schorfES/node-lintspaces/blob/master/lib/constants/ignorePatterns.js) to handle language-specific comments and such. It also has out-of-the-box EditorConfig support.

**Comment by jedmao** [comment]
Otherwise, [`eclint`](https://github.com/jedmao/eclint) might be the tool you're looking for.

**Comment by xuhdev** [comment]
[editorconfig-cf](https://github.com/xuhdev/editorconfig-cf) also has a validation feature.

**Comment by fulldecent** [comment]
This is a perfectly fine solution. Closing this issue. If further validation is possible beyond lintspaces then that would only be an improvement.

Hopefully the people at Circle CI will find lintspaces and apply it automatically when a .editorconfig is found.
