### ISSUE TITLE
Outreach request: Spacemacs editor

### ISSUE THREAD

**Issue by 526avijitgupta** [editorconfig/editorconfig#243]
Seems that adding [spacemacs](https://github.com/syl20bnr/spacemacs) support would really help their quickly growing community.

**Comment by 10sr** [comment]
I think it is a good idea, though I do not really familiar with spacemacs (you mean adding something called `layer` to the spacemacs official repository?).

I'd appreciate it if you do this for us :smiling_imp: 

@xuhdev what do you think?

**Comment by xuhdev** [comment]
Sure, why not? Just want to understand how to make it happen (and why supporting Emacs is not equal to supporting spacemacs?).

**Comment by 10sr** [comment]
Well, of course you can install and use EditorConfig with spacemacs without any changes for spacemacs.
Spacemacs has some [layers](https://github.com/syl20bnr/spacemacs/tree/master/layers), which can be thought as builtin modules, and adding editorconfig layer to this must be useful.

I think this is what @526avijitgupta means.

**Comment by 10sr** [comment]
I found that spacemacs had editorconfig layer before and it have already been removed.
https://github.com/syl20bnr/spacemacs/issues/2330
I think this is really reasonable: just adding editorconfig to the package list works well :100: 
Closing.

**Comment by xuhdev** [comment]
sounds good :)
