### ISSUE TITLE
add max line support

### ISSUE THREAD

**Issue by yuankui** [editorconfig/editorconfig#249]
which will start a new line if the line too long~

eg.
`max_line = 100`

**Comment by xuhdev** [comment]
Thanks for your suggestion. You can view the issue #89 . `max_line_length` is currently implemented in Emacs and Vim, which is similar to what you suggested. :)

**Comment by yuankui** [comment]
@xuhdev can it apply to Intellij IDEA?

**Comment by xuhdev** [comment]
@yuankui This issue should be reported to JetBrains as we do not maintain the EditorConfig features in JetBrains IDEs  :)

**Comment by yuankui** [comment]
@xuhdev 谢谢!
