### ISSUE TITLE
Color!

### ISSUE THREAD

**Issue by EnterTheNameHere** [editorconfig/editorconfig#250]
Hello,

what I would really like to see - support for color. What I see as the real ...issue... setting up across my editors is the coloring of code. I like dark background with custom colors, and to be honest most of the editors I come into contact with have terrible options to set colors.

They usually have premade solor sets, but creating your own one is lenghty process, often requiring having one editor with already created color set from which I can read a color from and set the same color into the new one.

They often don't support #hashed form, so I have to set R, G, B manually, one after another. If there would be support for exporting/importing color codes, it would be more than handy, it would be awesome...

I know there are a lot of potential issues, like global settings, settings for different programming languages/files and more I haven't think of, but color settings are the real deal when setting them across editors...

Also, imagine the possibility to share your configs with other users...

**Comment by MarcDiethelm** [comment]
Terrible idea. I'm quite sure editorconfig exists for reasons that are actually relevant to a software project like actual formatting of the committed code.

**Comment by xuhdev** [comment]
The idea of EditorConfig is to enforce unified settings, e.g. coding style, for a specific project. The idea of "color" is a developer's personal preference: whatever color one developer use does not affect another. You can specify the color in your own editor's settings---I don't see why that is not cool.

If you are looking for a universal theming tools across editors: I think it's a great idea! We should do a project for that.

**Comment by xuhdev** [comment]
FYI, I think CSS might be a good starting point to generate theme files for different editors.

**Comment by MarcDiethelm** [comment]
Apologies for my negative attitude here. I just felt that the project was being swamped with half-baked ideas and it kind of irked me. Although I believe that this request is off-topic for this project, universal themeing across editors would be a great thing to have!

**Comment by xuhdev** [comment]
@MarcDiethelm Just found [koeeoadi](https://github.com/seanirby/koeeoadi), which may be relevant.
