### ISSUE TITLE
insert_final_newline = true not adding line to the end of the file - Webstorm

### ISSUE THREAD

**Issue by tomenden** [editorconfig/editorconfig#254]
```
[*]

insert_final_newline = true
```
Does not add a new line to the end of the file. The rest of the rules seem to be working fine

**Comment by xuhdev** [comment]
Please report the issue to [JetBrain](https://github.com/JetBrains/intellij-community/tree/master/plugins/editorconfig). We do not maintain the JetBrain plugin.
