### ISSUE TITLE
Support autosave flag

### ISSUE THREAD

**Issue by bencates** [editorconfig/editorconfig#255]
Would it be possible to add a flag to disallow autosave for certain filetypes?

**Comment by xuhdev** [comment]
Autosave is more like a developer's personal preference rather than a rule that a team should enforce on individual developers. Perhaps you can enable this feature for your editor, instead of enforcing it with EditorConfig?

**Comment by cassidyjames** [comment]
The idea behind disabling it does make sense per project, though; if a project's workflow relies on tooling that runs when files are changed, autosave could wreak havoc on things. However, the developer might want autosave enabled on all other projects (that don't have watch tasks).

**Comment by jedmao** [comment]
This seems like more of an edge case.

**Comment by xuhdev** [comment]
Closing.
