### ISSUE TITLE
how to select all configuration files (files that ends with rc)?

### ISSUE THREAD

**Issue by dcdeiv** [editorconfig/editorconfig#256]
In my .editoconfig file I want to select all configuration files like .bowerrc, .jscsrc, .jshintrc and so on. The file must begin with a dot and end with rc.

I tried with [.*rc] but it does not work!

How can I select all those files in the .editorconfig file?

**Comment by xuhdev** [comment]
`[.*rc]` works for me. Which editor do you use? Which OS do you use? What does `which editorconfig` give you?

**Comment by dcdeiv** [comment]
I use ATOM on Xubuntu 15.10 x86, editorconfig plugin v1.2.4

Simply when I edit the `.editorconfig` rule for `[.*rc]` it won't do anything, it will keep on using the atom configurations.

**Comment by xuhdev** [comment]
@dcdeiv I've no idea... can you report to the ATOM plugin bug tracker? https://github.com/sindresorhus/atom-editorconfig/issues
