### ISSUE TITLE
Option to turn off max_line_length explicitly

### ISSUE THREAD

**Issue by jgkamat** [editorconfig/editorconfig#257]
For the case where you want a max_line_length of 'x' on all files except for certain ones (eg. documentation), this is pretty useful. For example

```ini
[*]
max_line_length=80

[*.md]
max_line_length=-1
```

Where -1 would turn off any automatic newlines or rulers added. [the docs](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties) say max_line_length only accepts positive integers as of now, so I'm pretty sure this behavior isn't present already.

**Comment by xuhdev** [comment]
@jgkamat I'll make it `off` for turning off this feature. I want to reserve the negative numbers for some other uses in the future. Do you agree?

**Comment by jedmao** [comment]
The same doc that you referenced also says to use `max_line_length = off` to unset.

**Comment by jgkamat** [comment]
Will this change break existing editorconfig browsers (a crash?) Otherwise this works perfectly!

**Comment by jedmao** [comment]
Oh. Well, I believe you could equally set it to `ignore` or `skip`. Basically, anything other than digits should turn it off. Isn't that correct, @xuhdev?

**Comment by xuhdev** [comment]
@jedmao Techniquely yes, we just standardize it since it's not that widely supported yet.

**Comment by xuhdev** [comment]
@jgkamat no crash :)

**Comment by jgkamat** [comment]
Cool, thanks! I'm closing this now since this isn't an issue here anymore.

**Comment by skorokithakis** [comment]
Could we reopen this? It seems that `off` currently is the same as simply not setting the option at all, whereas I want my `.editorconfig` file to mandate *no word wrapping at all* for files.
