### ISSUE TITLE
Errors building npp plugin

### ISSUE THREAD

**Issue by ffes** [editorconfig/editorconfig#258]
Not sure where to add this issue, here or in https://github.com/editorconfig/editorconfig-notepad-plus-plus/

I am trying to build the plugin to create a solution for https://github.com/editorconfig/editorconfig-notepad-plus-plus/issues/2, but I get link errors.

I have downloaded the 0.12.0 windows x86 binaries from SF.net (dated 2015-01-01) and started cmake (v3.5.2) with the full path to the directory where I extracted., as described in the README.

When I build the complete solution in VS2013, I get **a lot** of compile and link errors in VS2013.

Trying to narrow it down, I only build `NppEditorConfig_unicode` because that is what I need. Compiling works just fine, but I get these link error. What did I do wrong?

```
1>editorconfig_static.lib(ec_glob.c.obj) : error LNK2019: unresolved external symbol _pcre_compile referenced in function _ec_glob
1>editorconfig_static.lib(ec_glob.c.obj) : error LNK2019: unresolved external symbol _pcre_exec referenced in function _ec_glob
1>editorconfig_static.lib(ec_glob.c.obj) : error LNK2019: unresolved external symbol _pcre_free referenced in function _ec_glob
```

Obviously I miss PCRE, but I can't find any reference in the README of the plugin nor in the README of core-c.

**Comment by xuhdev** [comment]
This part is mentioned in the [INSTALL](https://github.com/editorconfig/editorconfig-core-c/blob/master/INSTALL.md) file of the editorconfig core. Unfortunately, this is how static library works: you have to prepare all of the dependencies. I can add some documentation later, but pretty much that's it: build the static pcre library and link both together. I consider this as a Notepad++ plugin documentation bug.

**Comment by xuhdev** [comment]
For your convenience, to solve the issue you pointed to, you can just use the core library of 0.11.x, which does not depend on pcre. I will build the plugin against the latest version and release the binary.

**Comment by ffes** [comment]
Tnx, The 0.11.5 helps a lot! I have a working build environment now.

Stupid of me not to read the INSTALL you mentioned.
