### ISSUE TITLE
Autoformatting for *.hbs does not work

### ISSUE THREAD

**Issue by dennis-f** [editorconfig/editorconfig#259]
When applying rules for **.hbs-files** it will only apply the rules to lines using handlebars syntax. HTML Syntax is not formatted via Editorconfig but with the Styles PHPStorm which should be overidden. 

__Renaming *.hbs to *.html solves this behavior.__

### .editorconfig
```ini
# EditorConfig helps developers define and maintain consistent
# coding styles between different editors and IDEs
# editorconfig.org

root = true

[*]
indent_style = space
indent_size = 2
```

### `space_indent=4`
```html
{{#if something}}
    <div class="button">
        {{#foo bar}}
            <img src="{{image-url "foo-bar"}}"/>
        {{/foo}}
    </div>
{{/if}}
```

### `space_indent=2`
```html
{{#if something}}
    <div class="button">
      {{#foo bar}}
          <img src="{{image-url "foo-bar"}}"/>
      {{/foo}}
    </div>
{{/if}}
```

**Comment by jedmao** [comment]
@dennis-f I think you need to create an issue at https://youtrack.jetbrains.com/issues.

**Comment by jedmao** [comment]
@denofevil ^^

**Comment by denofevil** [comment]
@jedmao, thanks for mentioning. Will try reproducing this, issue in youtrack would be awesome

**Comment by dennis-f** [comment]
sorry, can't right now. feel free to cite my post. thanks.

**Comment by denofevil** [comment]
@dennis-f, sorry it took so long, I've created [an issue](https://youtrack.jetbrains.com/issue/IDEA-156914) in YouTrack, feel free to watch it.
