### ISSUE TITLE
Add a way to undefine the tab_width property

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [editorconfig/editorconfig#262]
I would like for a "standard" editorconfig file for many projects that have different files.

I want by default to have `indent_style = space` and `indent_size = 4` for all files, except for a couple, most notably makefiles, that are broken if TAB is not used. But I don't want to override the tab width for the makefiles, I want to use the user's default (as the beauty of using tabs is anyone can configure their editor to show as many spaces as they like for a tab).

The problem is if I include the `indent_size = 4` in `[*]` I get the default `tab_width = 4` too and there is no way to say for example `tab_width = undefined`.
##

**Comment by jedmao** [comment]
I've always felt it strange that the `tab_width` setting would pull from the `indent_size` for this very reason. Definitely a discussion to be had here.

**Comment by xuhdev** [comment]
If you set `tab_width` to be `none` or anything else undefined, it should be ignored by the plugins.

**Comment by leandro-lucarella-sociomantic** [comment]
Mmm, I'll try it, but I didn't see that mentioned anywhere...

**Comment by leandro-lucarella-sociomantic** [comment]
OK, using `tab_width = none` works, maybe it should be documented somewhere?

**Comment by loechel** [comment]
the current documentation (https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#current-universal-properties) says that ``property = unset`` resets this property.

so I guess that would mean something like:

    [*]
    indent_style = space
    indent_size = 4

    [Makefile]
    indent_style = tab
    indent_size = unset
    tab_width = unset

should work for your case.

**Comment by leandro-lucarella-sociomantic** [comment]
OK, perfect, this seems to work and documented now, I'll close, I don't see a reason to keep it open.

**Comment by leandro-lucarella-sociomantic** [comment]
Thanks!
