### ISSUE TITLE
Export JetBrains "Code Style" rules to .editorconfig

### ISSUE THREAD

**Issue by Vadorequest** [editorconfig/editorconfig#263]
For those who like JetBrains product (PhpStorm, WebStorm, ...) and would like to have a way to export the IDE config to a .editorconfig file, know that there you can vote here: https://youtrack.jetbrains.com/issue/WEB-15687

Sadly, the feature hasn't been implemented yet, and would be really useful for many people.

_This is not a proper editorconfig issue, but since it is not that easy to find that link, maybe you'll decide to keep it open until it is released on JetBrains!_
##

**Comment by rquadling** [comment]
[Voting is now closed.](https://youtrack.jetbrains.com/issue/WEB-15687#comment=27-1505808)

**Comment by xuhdev** [comment]
Looks like has already been implemented.

**Comment by JanisE** [comment]
xuhdev, where is that option? If I open the (default) settings, Code Style, and then open the scheme commands, the "Export" exports in an XML format, not .editorconfig.

**Comment by adevinedosh** [comment]
@JanisE , took a while for me to find it, too:

In Settings under Editor > Code Style, at the bottom of that dialog there is an EditorConfig section with an "Enable EditorConfig Support" checkbox and an Export button

**Comment by dandohotaru** [comment]
and nowadays (2018.1) the option resides in Resharper > Settings > Code Editing > General Formatter Style

**Comment by hamjo** [comment]
What would be the way to do so in Resharper 2018.2? The settings path you mentioned does have an "Enable EditorConfig Support" checkbox but doesn't seem to have an Export button...

**Comment by Sebazzz** [comment]
This is still open for ReSharper, but marked critical: https://youtrack.jetbrains.com/issue/RSRP-468159
