### ISSUE TITLE
New Lua Core Library and editor plugin

### ISSUE THREAD

**Issue by randstr** [editorconfig/editorconfig#270]
I created a new EditorConfig Lua Core library and also a new [Textadept](https://foicica.com/textadept/index.html) plugin:

https://github.com/randstr/editorconfig-core-lua
https://github.com/randstr/textadept-editorconfig

It's passing all tests and pretty much feature complete. I think they would be useful to a wider audience at this point.

Could these two repositories be added to the EditorConfig project website please?

**Comment by xuhdev** [comment]
Awesome! I've created a new repository for the core library. Do you think it's a better idea to name the plugin repo as editorconfig-textadept?

**Comment by randstr** [comment]
I think it's absolutely a better idea to rename, done. Thanks!

**Comment by xuhdev** [comment]
OK, would you like to grant me the admin permission of both of the repos? Then I can make the ownership transfer. Thanks!

**Comment by randstr** [comment]
Yes, sure, my knowledge of some Github features is quite limited so I might need a bit of handholding :grinning:, but  I think I got that right?

**Comment by xuhdev** [comment]
@randstr I think I need the "admin" privilege to move the repos... But you can just do clone and push if you don't care about the redirection -- I've created two empty repositories with the same names under editorconfig and leave the decision up to you.

**Comment by randstr** [comment]
I'm fine either way but transferring the repo makes sense to me. How can I assign the admin privilege to you? I assumed I had to invite you as a collaborator first and then do that...

Seems like it should just be possible to initiate the transfer from my side and then an owner/admin for an organization can choose to accept or not, but apparently that's not how it works.

**Comment by randstr** [comment]
Or should I just push my code to the new empty repositories?

**Comment by xuhdev** [comment]
@randstr Yes, you can just do the push. There is no issues or pull requests to keep anyway.

**Comment by xuhdev** [comment]
I've done the "clone and push" job. You should have admin access to the two new repos. Thanks!

**Comment by randstr** [comment]
@xuhdev Cool, thanks. I took the liberty of renaming the one repo to "editorconfig-textadept" like you suggested. I like that name better to fit with the current project structure.
