### ISSUE TITLE
Add a link to the textadept plugin

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig#271]
@ineptcat We need a new logo now :)

https://github.com/editorconfig/editorconfig-textadept

**Comment by xuhdev** [comment]
cc @randstr

**Comment by ineptcat** [comment]
![textadept_t](https://cloud.githubusercontent.com/assets/2091281/18823003/58533fbc-836a-11e6-959a-74bd42215fbc.png)

**Comment by xuhdev** [comment]
That's so cool! Thanks!

**Comment by randstr** [comment]
That's awesome, thanks a lot!
