### ISSUE TITLE
Add TortoiseMerge / TortoiseGitMerge in No Plugin editor

### ISSUE THREAD

**Issue by linquize** [editorconfig/editorconfig#272]
editorconfig.org website has a list of "No Plugin" editors.

TortoiseMerge (from TortoiseSVN) / TortoiseGitMerge (from TortoiseGit) have built-in support for editorconfig.

Please add.

**Comment by xuhdev** [comment]
Thanks! I didn't know it before! Do you have a link to elaborate that?

**Comment by linquize** [comment]
TortoiseGitMerge: https://tortoisegit.org/docs/tortoisegitmerge/tmerge-dug-settings.html#tmerge-dug-settings-main
**Enable EditorConfig** checkbox should be checked.
TortoiseMerge (from TortoiseSVN) has the same functionality but the doc is not updated.

**Comment by xuhdev** [comment]
@ineptcat Could you help with this logo again? Thanks! https://tortoisegit.org/

**Comment by ineptcat** [comment]
@xuhdev thanks for the tag! it's the best way to get a hold of me. had some spare time so i decided to bang this out.
![tortoisegit_t](https://cloud.githubusercontent.com/assets/2091281/18856842/81dbc8be-8413-11e6-9501-294af8436fc6.png)

**Comment by linquize** [comment]
Quick response for the logo!

**Comment by xuhdev** [comment]
Wow, thanks for the lightning response!
