### ISSUE TITLE
Add Gogs to section of projects that support editorconfig natively

### ISSUE THREAD

**Issue by andreynering** [editorconfig/editorconfig#273]
[Gogs](https://github.com/gogits/gogs) currently natively support editorconfig for:

- [Showing files and diffs](https://github.com/gogits/gogs/pull/3241)
- [Creating or editing files directly in the browser](https://github.com/gogits/gogs/pull/3512)

Support for even more features may come in the future.

**Comment by xuhdev** [comment]
@ineptcat @treyhunner

**Comment by ineptcat** [comment]
![gogs_t](https://cloud.githubusercontent.com/assets/2091281/18823504/95ee50be-836f-11e6-80ad-1f984b0b6792.png)
