### ISSUE TITLE
Feature request: Soft wrapping

### ISSUE THREAD

**Issue by inf3rno** [editorconfig/editorconfig#275]
In my current case I'd like to turn on soft wrapping by html and md files, while I don't want to use it by js files in the Webstorm editor. I am sad that this feature is not supported by editorconfig, so I have to turn on soft wrapping by the active editor every time I open a html or md file. :-( I can't understand why this could not be a feature in https://github.com/editorconfig/editorconfig/issues/168 Any clues?
##

**Comment by xuhdev** [comment]
For Webstorm issues, you need to report to [JetBrain](https://youtrack.jetbrains.com/issues/IDEA). You can consider asking for setting soft wrapping equal to what `max_line_length` is set.

**Comment by inf3rno** [comment]
@xuhdev Afaik. `max_line_length` is for hard wrapping, and by resizing the window it would break, or at least we should recalculate it by window size changes. Am I right or is there a workaround for soft wrapping?

**Comment by xuhdev** [comment]
Sorry I thought you would mean specify hardwrapping and softwrapping at the same time. IMO visual wrapping is much like a personal preference which you can set for your own editor, while the focus of `editorconfig` is to unify coding style for all people in the project with different programming tools. That is, I don't see a need to carry an `.editorconfig` file which specifies visual effects along with a project. What do yo think?

**Comment by inf3rno** [comment]
@xuhdev I am not sure about the goals of this project, I just asked a question on SO, and they pointed me in this direction... http://stackoverflow.com/questions/39945392/soft-wrap-by-markdown-only

**Comment by xuhdev** [comment]
Cloing now...
