### ISSUE TITLE
Rider support

### ISSUE THREAD

**Issue by Extrawurst** [editorconfig/editorconfig#276]
I just tried to install the plugin manually that exists for php storm but it does not work for rider. can you support rider with that plugin aswell?
https://www.jetbrains.com/rider/

**Comment by xuhdev** [comment]
JetBrains maintain the plugin indepedently from us. Can you report a bug on [JetBrain's bug tracker](https://youtrack.jetbrains.com/issues/IDEA)?

**Comment by Extrawurst** [comment]
Thanks, done: https://youtrack.jetbrains.com/issue/RIDER-2864
