### ISSUE TITLE
Do more specific rules override more general ones?

### ISSUE THREAD

**Issue by jamesarosen** [editorconfig/editorconfig#278]
The [file format details page](http://editorconfig.org/#file-format-details) describes in detail how multiple `.editorconfig` files are merged. But it doesn't specify how multiple _rules_ within a file are handled.

In our project, we have
```
[*]
insert_final_newline = true

[*.hbs]
insert_final_newline = false
```

In [editorconfig-sublime](https://github.com/sindresorhus/editorconfig-sublime), this does what I would expect: all files except `*.hbs` files have a final newline. In [atom-editorconfig](https://github.com/sindresorhus/atom-editorconfig), all files have a final newline.

Somewhat related to #220

**Comment by xuhdev** [comment]
Yes, the `insert_final_newline = false` is supposed to win. This looks like a bug in the editor plugin, so please report the issue [there](https://github.com/sindresorhus/editorconfig-sublime/issues).

**Comment by jamesarosen** [comment]
Does it win because it's after or because it's more specific?

**Comment by xuhdev** [comment]
It's after.
