### ISSUE TITLE
Wildcard documentation

### ISSUE THREAD

**Issue by jonathantneal** [editorconfig/editorconfig#283]
The wildcard documentation at http://editorconfig.org/#wildcards:

> `*`	Matches any string of characters, except path separators (/)

However, `[*]` should match all files, recursively, including paths with separators, correct?

As I understand it, this same recursive matching style applies to `[*.py]`, `[*.{js,py}]`, etc until one introduces a `/`. This would be why the examples show patterns like `[lib/**.js]` versus `[lib/*.js]`?

Have I misunderstood the documentation, or is it incorrect? If it is incorrect, would you explain how globbing works in EditorConfig? To me, the documentation suggests globbing works like [node-glob](https://github.com/isaacs/node-glob#glob-primer).

**Comment by xuhdev** [comment]
`[*]` doesn't match separators. Yes, your understanding is correct. Do you have any particular strange pattern you observed that does not match what you expected?

**Comment by jonathantneal** [comment]
@xuhdev, would `[*.js]` match files in subdirectories, like `foo/index.js`? That’s the behavior I experience. However, has that pattern technically matched against a `/` separator? Or do I misunderstand something?

Similarly, would `[foo/*.js]` match files in deeper subdirectories, like `foo/bar/index.js`?

**Comment by xuhdev** [comment]
@jonathantneal  All matching is done in the directory of the target file, not the directory of the `.editorconfig` file. Does it answer your question?

**Comment by jonathantneal** [comment]
I think I understand. Is there a name for this matching style, so I can understand when I’m using this method versus the one from, say, node-glob?

**Comment by xuhdev** [comment]
I've never heard of that term before, but it looks like exactly what it is...

**Comment by astapler** [comment]
I have the same question as @jonathantneal - sorry I don't understand the answers above. To match any js files under a directory, including subdirectories within
for example: `foo/bar/file.js` and `foo/file.js`
should I write: `[foo/*.js] `or `[foo/**.js]`?

**Comment by TomasMalecek** [comment]
Usually, an .editorconfig file is in the root of a Git repo. https://editorconfig.org/ itself says that the format is similar to gitignore. If I have `foo/bar/lib/file.js` and `lib/file.js`, should the pattern `lib/*.js` match only the latter, or both? In gitignore, it would match both. If it matches only the latter and I want both, do I need to specify the pattern as `**/lib/*.js`? If it matches both and I want only the latter, is there a way to achieve it, e.g. `/lib/*.js` (as in gitignore)?

I know I can verify the results experimentally, but the question aims at the specification of the EditorConfig format. There may be other implementations and such ambiguities in the spec may jeopardize the portability of .editorconfig files. Also, the current implementation may contain bugs -- or rather unwanted behavior which may be changed later, as unspecified behavior cannot really be called a bug.

**Comment by TomasMalecek** [comment]
BTW, I checked a similar case in VS Code 1.85.2. Not sure which implementation of EditorConfig it uses.

I used this content of `file.xml`:
```
<?xml version="1.0"?>
<Root />
```

... and this content of `.editorconfig`:

```
root = true

[*]
indent_style = space
indent_size = 4

[*.xml]
indent_size = 2
```

I put the .editorconfig file in a folder and several copies of file.xml in the folder and its sub-folders:
```
$ find -type f
./.editorconfig
./file.xml
./folder/lib/file.xml
./lib/file.xml
./lib/folder/file.xml
```

I executed VS Code in the top folder and checked the indent size displayed in the bottom bar for each XML file. Then, I repeated that for different patterns in the second section of the .editorconfig. A checkmark means the pattern matched the file (indent size was 2), and a cross means it did not match (indent size was 4).

| Pattern\File    | ./file.xml | ./folder/lib/file.xml | ./lib/file.xml | ./lib/folder/file.xml |
|-----------------|:----------:|:---------------------:|:--------------:|:---------------------:|
| `*.xml`         | ✔          | ✔                     | ✔              | ✔                     |
| `**.xml`        | ✔          | ✔                     | ✔              | ✔                     |
| `/*.xml`        | ✔          | ❌                    | ❌             | ❌                    |
| `/**.xml`       | ✔          | ✔                     | ✔              | ✔                     |
| `lib/*.xml`     | ❌         | ❌                    | ✔              | ❌                    |
| `lib/**.xml`    | ❌         | ❌                    | ✔              | ✔                     |
| `/lib/*.xml`    | ❌         | ❌                    | ✔              | ❌                    |
| `/lib/**.xml`   | ❌         | ❌                    | ✔              | ✔                     |
| `**/lib/*.xml`  | ❌         | ✔                     | ✔              | ❌                    |
| `**/lib/**.xml` | ❌         | ✔                     | ✔              | ✔                     |

I find it noteworthy that the leading slash seems to have no effect except in the `/*.xml` case. Gitignore patterns with a leading slash start match only in the repo root, and EditorConfig mostly displays a different behavior.

Also, the difference between `*` and `**` can be seen, and the difference between `*` in a pattern containing a slash a not containing a slash, too.
