### ISSUE TITLE
Application for board membership

### ISSUE THREAD

**Issue by florianb** [editorconfig/editorconfig#284]
I applying to become a board member of editorconfig.

I want to help pushing editorconfig forward. It is already a widely accepted standard and attracts a growing user base.

I am using editorconfig for a few years now and i am grateful it exists. I am using the Atom editor in my daily work and i started relying on editorconfig with Atom's package atom-editorconfig. Since i was missing functionality in the past i started to help maintaining atom-editorconfig.

I would say i made atom-editorconfig a bit more mature and surely more compliant. Currently the work on atom-editoroconfig shifts more often to the standard-definition, since we came to a point at which is likely that changing any functionality would violate the standard.

If i would be asked what i am after, i'd say i would like to see editorconfig becoming explicit (as i tried to explain in #279) allowing the standard to provide a single source of information (with no room for interpretation) for developers and users. I would also tend to overthink any rule where a compliant enforcement is doubted.

Feel free to ask my any question.

**Comment by xuhdev** [comment]
@editorconfig/board-member This is the first time that we are going to cast our votes. Remember we have two weeks (until Dec 27 GMT-12 23:59)

**Comment by jedmao** [comment]
👍 from me.

**Comment by johan** [comment]
👍  here, too.

**Comment by xuhdev** [comment]
👍

**Comment by sindresorhus** [comment]
👍

**Comment by xuhdev** [comment]
Congrats! You are in.

**Comment by florianb** [comment]
Hooray.. 🎉 

Thank you very much! 👏
