### ISSUE TITLE
Unite one central editorconfig.md containing a human readable standard definition

### ISSUE THREAD

**Issue by florianb** [editorconfig/editorconfig#286]
I'd like to discuss introducing a single `editorconfig.md` kindly formatted which contains the editorconfig-format description in a human readable way.

It might contain the following sections:

1) Quick Start
2) Reference (containing the explicit rules and examples per rule)
3) Appendix (containing the machine readable specification)

This would enable us to

- comprehend changes
- discuss changes in a PR
- embed the sections of that document in the website

**Comment by xuhdev** [comment]
What is the "**machine readable specification**"?

**Comment by florianb** [comment]
If something like the EBNF is coming this could be the grammar. I would appreciate if this in general is being discussed and receives some additional thoughts. ☕️

**Comment by cxw42** [comment]
Can this one be closed now that we have the specification repo?

**Comment by florianb** [comment]
Sure - already wrapping my mind around this.
