### ISSUE TITLE
Use `unset` as the standard value to turn off any option if applicable.

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig#287]
This is a voting only thread.

Discussion should be at #285 .

Let's decide it before Dec 29 GMT -12 23:59

### `unset` - disables treatment of Property by editorconfig

The `unset`-keyword can be used to explicitly disable editorconfig's treatment for the given property. It is reserved so that there is confidence it shall not be used in the future for something else.

```ini
root = true;

[*]
indent_style = space
indent_size = 4
end_of_line = lf
insert_final_newline = true

[*.md]
indent_style = unset
indent_size = unset
```

In this case, for files matching `*.md`, editorconfig does not set `indent_size` and `indent_style`, while for the other files it does.

**Comment by jedmao** [comment]
👍

**Comment by florianb** [comment]
:+1:

**Comment by xuhdev** [comment]
👍

**Comment by ffes** [comment]
👍

**Comment by jedmao** [comment]
👍

**Comment by sergeyklay** [comment]
👍

**Comment by chiefengineer** [comment]
I'm with xuhdev and prefer 'off' to 'unset"

**Comment by sindresorhus** [comment]
👍

**Comment by xuhdev** [comment]
Done, I've added it to the wiki.
