### ISSUE TITLE
Feature Request: allow_leading_comma

### ISSUE THREAD

**Issue by chiefengineer** [editorconfig/editorconfig#289]
Sql Server Management Studio, when creating scripts for use/storage, will write multi-column entities in the following format:

[First Column Definition]
, [Second Column Definition]
, [Third Column Definition]

etc.
The thing to pick up on here is that any multi-column other than the first column definition will be displayed with a leading comma (,) character.
It would be very nice if this could be applied to lists of items in source code e.g. property initializers (C#), 
parameter values (almost any language), etc.
For a parameter list it could be (and this is a C# example):
```
public void SomeFunction
(
  Param1
  , Param2
  , Param3
)
{
  List<string> someList = 
    new List<string>
    {
      "Item1"
      , "Item2"
      , "Item3"
    };
  // More code follows...
}


```
Suggested values for allow_leading_comma
- true
- false
- as_is (don't change anything)

**Comment by jedmao** [comment]
EditorConfig is not intended to define rules for language-specific syntax. Instead, you need a linter for that language in cases like these. EditorConfig is for defining language-agnostic rules that apply to any/all languages or even plain text, so this request is out of scope.
