### ISSUE TITLE
Feature request: start_block_style and end_block_style

### ISSUE THREAD

**Issue by chiefengineer** [editorconfig/editorconfig#290]
Some of the suggested properties e.g. curly_bracket_next_line and indent_brace_style and spaces_around_brackets seem to be a little too language-specific and worse, indent_brace_style would require me to not only know the style, but who invented it! Granted, Wikipedia will tell me but who wants to memorize K&$ vs Allman? Not me.
How about a more general property such as begin_block_style? This would allow the inclusion of folks that use languages like Delphi (which uses a "Begin"/"End" pair to delineate code blocks?
The complete set of properties might include the following:

`start_block_style="<some delimiter>":<code location>:<style>:<allow inline comment>:<pad left>:<pad right>:<vertical tab before>:<vertical tab after>`

`"<some delimiter>"` - Many languages allow more than one code block start delimiter e.g. in Delphi code blocks start with the word "begin", in C# array declarations start with a left bracket ( [ ) and property initializers use a left brace ( { ), most languages use a left parentheses ( ( ) to start parameter declarations. The delimiter is enclosed in double quotes.

`<code location>` - this entry can take on one of the following values:
 - declaration - when the delimiter is found in the declaration portion of a code statement.
 - body - when the delimiter is found in the body of a code statement.

`<allow inline comment>` - this entry can take on one of the following values:
 - true - allow an inline comment on the same line as the delimiter
 - false - do not allow an inline comment on the same line as the delimiter

`<style>` - this entry can take on one of the following values:
 - isolated - the delimiter is on its own line allowing no other code save inline comments.
 - inline - the delimiter is just part of the code declaration.
 - same_line - the delimiter is the first non white-space item on the line but allows other code to follow on the same line.
 - break_to_new_line_before - at the point in the code where the delimiter is found, insert a newline before the delimiter and place the delimiter and all following code on the next line, indented as specified.
 - break_to_new_line_after - at the point in the code where the delimiter is found, insert a newline after the delimiter and place the code that follows on the next line, indented as specified.
 - as_is - don't mess with the current formatting, pad and vertical tab values will be ignored.

`<pad left>` - after the style has been applied to the location of the delimiter, insert the specified number of indent_size indents relative to the beginning of the declaration or the previous line of code in the body BEFORE the delimiter is rendered. If an "s" modifier is used e.g. 3s, instead of using indent_size indents, the value is converted to spaces and the appropriate number of spaces will be inserted or that number of spaces will be converted to the appropriate number of tab_size + left over spaces and inserted as appropriate. If a combination of indent_size indents and spaces is desired, use the "i" modifier to identify indents e.g. 3 indents and 1 space would be set as 3i1s.

`<pad right>` - after the style has been applied, the pad_left value applied, the delimiter itself rendered, add the specified right padding to the delimiter AFTER the delimiter has been rendered. If an "s" modifier is used e.g. 3s, instead of using indent_size indents, the value is converted to spaces and the appropriate number of spaces will be inserted or that number of spaces will be converted to the appropriate number of tab_size + left over spaces and inserted as appropriate.  If a combination of indent_size indents and spaces is desired, use the "i" modifier to identify indents e.g. 3 indents and 1 space would be set as 3i1s.

`<vertical tab before>` - after the style has been applied but BEFORE any padding is applied, insert the specified number of newlines, then render the padding, then the delimiter, then the vertical_tab_after.

`<vertical tab after>` - number of newlines to be added after the delimiter has been rendered.

And, of course, the corersponding end_block_style property:

` end_block_style="<some delimiter>":<code location>:<style>:<allow inline comment>:<pad left>:<pad right>:<vertical tab before>:<vertical tab after>`

`"<some delimiter>"` - Many languages allow more than one code block end delimiter e.g. in Delphi code a program declaration ends with "end.", a method declaration ends with "end;" and a code block ends with "end" (the difference being that a program "end" ends with a period, a declaration "end" ends with a semi-colon and a code block "end" is just "end"). In C#, a declaration ends with just a right brace ( "}" ) but a statement block ends with a right brace and semi-colon ( "};} ). The delimiter is enclosed in double quotes.

`<code location>` - this entry can take on one of the following values:
 - declaration - when the delimiter is found in the declaration portion of a code statement.
 - body - when the delimiter is found in the body of a code statement.

`<allow inline comment>` - this entry can take on one of the following values:
 - true - allow an inline comment on the same line as the delimiter
 - false - do not allow an inline comment on the same line as the delimiter

`<style>` - this entry can take on one of the following values:
 - isolated - the delimiter is on its own line allowing no other code save inline comments.
 - inline - the delimiter is just part of the code declaration.
 - same_line - the delimiter is the first non white-space item on the line but allows other code to follow on the same line.
 - break_to_new_line_before - at the point in the code where the delimiter is found, insert a crlf before the delimiter and place the delimiter and all following code on the next line, indented as specified.
 - break_to_new_line_after - at the point in the code where the delimiter is found, insert a crlf after the delimiter and place the code that follows on the next line, indented as specified.
 - line_up - line up with the corresponding start delimiter. <pad left> values will be ignored.
 - as_is - don't mess with the current formatting, pad and vertical tab values will be ignored.

`<pad left>` - after the style has been applied to the location of the delimiter, insert the specified number of indent_size indents relative to the beginning of the declaration or the previous line of code in the body BEFORE the delimiter is rendered. If an "s" modifier is used e.g. 3s, instead of using indent_size indents, the value is converted to spaces and the appropriate number of spaces will be inserted or that number of spaces will be converted to the appropriate number of tab_size + left over spaces and inserted as appropriate. If a combination of indent_size indents and spaces is desired, use the "i" modifier to identify indents e.g. 3 indents and 1 space would be set as 3i1s.

`<pad right>` - after the style has been applied, the pad_left value applied, the delimiter itself rendered, add the specified right padding to the delimiter AFTER the delimiter has been rendered. If an "s" modifier is used e.g. 3s, instead of using indent_size indents, the value is converted to spaces and the appropriate number of spaces will be inserted or that number of spaces will be converted to the appropriate number of tab_size + left over spaces and inserted as appropriate. If a combination of indent_size indents and spaces is desired, use the "i" modifier to identify indents e.g. 3 indents and 1 space would be set as 3i1s.

`<vertical tab before>` - after the style has been applied but BEFORE any padding is applied, insert the specified number of newlines, then render the padding, then the delimiter, then the vertical_tab_after.

`<vertical tab after>` - number of newlines to be added after the delimiter has been rendered.

Code samples:

Delphi:
start_block_style="(" : declaration : break_to_new_line_before : false: 1 : 1s : 0 : 0
start_block_style="begin" : declaration : isolated : false : 1 : 0 : 2 : 1
end_block_style="end;" : declaration : line_up : true : -1 : 0 : 1 : 0
```
Function SomeFunction
  ( aParam: string): string


  begin

    (* some useable code goes here *)

end; // SomeFunction
```
What you see: the declaration was broken at the first encountered left paren in the declaration. Said left paren was indented 1 indent_size indent, the left paren rendered, a single space inserted and the rest of the code rendered on the same line. The "begin" has two newlines inserted and is indented one indent_size indent before rendering and a single newline after.
The "end" has been offset from the "begin" by -1 indents and is allowing inline comments.

C#:
start_block_style="(" : declaration : break_to_new_line_before : true : 0 : 0 : 0 : 1
end_block_style=")" : declaration : break_to_new_line_after : false : 0 : 0 : 1 : 1
start_block_style="{" : declaration : isolated : true : 0 : 0 : 1 : 1
end_block_style="}" : declaration : isolated : true : 0 : 0 : 1 : 0
start_block_style="{" : body : break_to_new_line_after : false : 0 : 0 : 0 : 0
end_block_style="}" : body : line_up : false : 0 : 0 : 0 : 0

```
public void someFunction
( // start param list here
  int someIntParam
  , string someStringParam

)

{

  List<string> someStrings =
    new List<string> {
                        "first value"
                        , "second value"
                     }

}
```
What you see: The start of the parameter declaration has been moved to the next line, the left paren isolated but allows inline comments. The right paren is isolated and has included a preceding newline. The starting brace is isolated and includes a preceding and following newline. The body of the code includes a left brace that is allowed to be part of the declaration and the closing brace is to line up with the opening brace.
The closing method brace is isolated and includes a preceding newline.

Javascript:
start_block_style="{" : declaration : break_to_new_line_after : false : 0 : 0 : 0 : 0
end_block_style="}" : declaration : isolated : false : 0 : 0 : 0 : 0
```
function myFunction(p1, p2) {
    return p1 * p2;              // The function returns the product of p1 and p2
}
```
What you see: The opening left paren is left on the same line as the rest of the declaration, the right paren is isolated.

**Comment by jedmao** [comment]
Again, you're getting into language-specific requests here. Sorry, but EditorConfig is not the place for this request.
