### ISSUE TITLE
[Question] SVG version of logo?

### ISSUE THREAD

**Issue by JimiC** [editorconfig/editorconfig#291]
Is there somewhere an SVG version of the logo?
We'ld really like to have it on [vscode-icons](https://github.com/robertohuertasm/vscode-icons).

**Comment by xuhdev** [comment]
@JimiC I'm not sure about it, but why an svg version? I don't see how a vector image is suitable for the logo...

**Comment by JimiC** [comment]
We are currently on a process to convert all PNG icons to SVG for `vscode-icons`, an extension for `vscode`. As you may know, you can zoom in and out on those IDE and an SVG provides better scaling.

**Comment by jedmao** [comment]
@JimiC you might be interested in the files [here](https://github.com/editorconfig/editorconfig-visualstudio/tree/master/src/EditorConfig.VisualStudio/Resources); though, the logo is intended to be kind of squiggly, so converting it to SVG would have a lot of nodes.

**Comment by jedmao** [comment]
I just converted the logo to SVG in CorelDRAW. I think it looks good at this size. Let me know if this isn't good enough:

[EditorConfig_Large.zip](https://github.com/editorconfig/editorconfig/files/680383/EditorConfig_Large.zip)

**Comment by JimiC** [comment]
AWESOME. Many many thanks @jedmao. You're the man.

Should be definitely added in your graphics collection. Others may look for it as well.
