### ISSUE TITLE
Enhancement for end_of_line support

### ISSUE THREAD

**Issue by TheUltimateDeployer** [editorconfig/editorconfig#292]
In projects with Git is the line feed setting often the plattform standard ("core.autocrlf" as descibed on https://git-scm.com/book/tr/v2/Customizing-Git-Git-Configuration). 
Editorconfig is currently only supporting a fixed setting which prevents the use of this Git functionality.
Leaving the end_of_line value out is also not an option because it should be desired that the plattform setting is used in text files.

I propose the new end_of_line value "autocrlf" which has the exact meaning of the Git setting.

KR Christian

**Comment by florianb** [comment]
Hi @TheUltimateDeployer - thanks for filing this idea.

I don't think this is possible. Git is, at first, applying on a lower level of the sources. Which means the files are manipulated to fit into the correct eol before the editor can read it. So even if you define something different than the Git settings, Git would reset it at the point you're adding the changes to the index. So in fact "Editorconfig [...] prevents the use of this Git functionality" should not be true.

Secondly, the end_of_line-property should assure that every file leaving the editor conforms to the set line ending on whichever platform you're are editing it.

If editorconfig shouldn't touch the line endings, remove the setting or explicitly unset it. After that point line endings are handled by your editor and overridden by Git anyways.

If you face unexpected behavior there is probably a bug.

**Comment by TheUltimateDeployer** [comment]
Hi,

thanks for the feedback. I made this proposal based on some observations in a project.
There is the following situation: 
We use the Git autocrlf setting in Git and edit the files on different platforms (Windows / Linux).

What happens with one of the existing constants (e.g. Windows CRLF):
1. If I verify the .editorconfig on Unix after checkout (no editor had a chance to change it) then it fails because Git checks them correctly out with LF. 
2. If the editor converts it based on on the editorconfig settings to another line ending than the platform setting then it is risky. Not all editors support "Editorconfig" or have the corresponding plugin installed. Using such an editor after the conversion can lead to mixed line endings. 

Not setting this option is also not an option:
Mixed endings in one file (can also happen on Windows using Cygwin's vi ;-)) won't be changed by Git anymore (http://stackoverflow.com/questions/29793339/git-with-autocrlf-true-checks-out-files-with-mixed-line-endings-as-is). There are tools which compare or render text files.

The reason to introduce a new value is a Maven plugin that I will release soon on Github.
It enforces the conformance of the files according to the editorconfig values.
In our case the CI process (Maven) will refuse files in pull requests which don't conform to the editorconfig.

An official support of such a setting is needed in order to configure the editors properly (Unix->LF, Windows->CRLF ...)

**Comment by jedmao** [comment]
I can't find it right now, but we talked about something similar in the past. I think it would be better implemented as `end_of_line = os` though. It doesn't need to know anything special about the `.gitattributes` file or even Git. It just needs to know to apply the OS newline character, whatever that is.

**Comment by TheUltimateDeployer** [comment]
This proposal is a duplicate to #226. 
I will close it.
