### ISSUE TITLE
Add micro editor plugin

### ISSUE THREAD

**Issue by 10sr** [editorconfig/editorconfig#294]
I created a new editorconfig plugin for [micro](https://github.com/zyedidia/micro) editor 💪 
https://github.com/10sr/editorconfig-micro

If it is ok adding this repository to editorconfig org would be nice!

**Comment by jedmao** [comment]
I think we would need our EditorConfig artist to create something for this new plugin. @treyhunner, who did the artwork again?

@10sr, is this the correct project? https://github.com/zyedidia/micro

**Comment by treyhunner** [comment]
@ineptcat does the logos. Looks like Micro's logo is a μ.

**Comment by xuhdev** [comment]
@ineptcat Can you also license the logos you have made, please? Someone has asked on the mailing list for the permission to use them. Thank you!

**Comment by 10sr** [comment]
> is this the correct project? https://github.com/zyedidia/micro

@jedmao Yes, I wrote this plugin for this editor.

**Comment by ffes** [comment]
Isn't https://micro-editor.github.io/ a better link?

Off topic: Hadn't heard of micro until this issue was opened, but it looks like a promising new editor, especially for people new to the command line.

**Comment by 10sr** [comment]
> Isn't https://micro-editor.github.io/ a better link?

I see!
I agree this is better for users.

**Comment by ineptcat** [comment]
![micro_s](https://cloud.githubusercontent.com/assets/2091281/21917020/761f475e-d8f9-11e6-8c96-1d5c259dadd8.png)

@treyhunner thanks for pinging me - best way to reach me for a logo.
@xuhdev all free to use with attribution - link to squirrelmuffins.com (like on the website). more specifically CC-BY-SA (attribution, sharealike)
