### ISSUE TITLE
Add Plugin Guidelines for Each Property

### ISSUE THREAD

**Issue by jedmao** [editorconfig/editorconfig#295]
I propose adding a section to the [Plugin-How-To section of the wiki](https://github.com/editorconfig/editorconfig/wiki/Plugin-How-To) that offers guidelines about how to implement each EditorConfig property.

Some rules are best implemented the moment you open a file, but others may only apply on each file save. We probably need some clarity there.

To kick-off the discussion, let me make a list and we can modify it as the discussion evolves.

## `indent_style`

1. When opening/switching to a file, apply built-in editor setting.
1. If no built-in editor setting, do nothing. Do not attempt to fix indent style with manual operations.

## `indent_size`

1. When opening/switching to a file, apply built-in editor setting.
1. If no built-in editor setting, do nothing. Do not attempt to fix indent size with manual operations.

## `tab_width`

1. When opening/switching to a file, apply built-in editor setting.
1. If no built-in editor setting, do nothing. Manual operations do not apply to this property.

## `end_of_line`

1. When opening/switching to a file, apply built-in editor setting. In some editors, this will mark the file as dirty.
1. If no built-in editor setting, apply built-in editor operation on file save.
1. If no built-in editor operation, apply manual operation on file save or do nothing.

## `charset`
1. When opening/switching to a file, apply built-in editor setting.
1. If no built-in editor setting, apply manual operation on file save or do nothing.

## `trim_trailing_whitespace`
1. Do not attempt to fix trailing whitespace when opening/switching to a file.
1. Apply built-in editor setting on file save.
1. If no built-in editor setting, apply manual operation on file save or do nothing.

## `insert_final_newline`

1. Do not attempt to insert a final new line when opening/switching to a file.
1. On file save, apply built-in editor setting.
1. If no built-in editor setting, apply manual operation on file save or do nothing.

**Comment by xuhdev** [comment]
Sure, I'm totally up for it.

**Comment by ffes** [comment]
Just a question.

What if for instance the eol in the file is `crlf` and the file is opened and `.editorconfig` sees it should be `lf`. Should the plugin convert silently, convert and report, just report, offer an option to do the conversion. We should say something about that as well.

**Comment by jedmao** [comment]
It would be pretty annoying if you get a prompt every time someone opens up a file with mixed line endings. I think the description above is sufficient. The only thing you should do on file open is activate the editor setting. I'm done editors (e.g., vscode), this will mark the file as dirty. In other editors, it won't, so you wait until they save the file to perform any eol conversion. @ffes, does that make sense?

**Comment by jedmao** [comment]
Maybe we should say "activate" instead of "apply" editor setting? Would that be more clear?

**Comment by jedmao** [comment]
I've added a [Plugin Guidelines](https://github.com/editorconfig/editorconfig/wiki/Plugin-Guidelines) wiki page with a reference to it on the [Home](https://github.com/editorconfig/editorconfig/wiki) wikie page. Feel free to continue any discussion points here, but I'm closing the issue for now.

**Comment by xuhdev** [comment]
@jedmao Thanks!
