### ISSUE TITLE
Create a wiki page, or make a webpage that accepts PR, for suggesting default EditorConfig files for popular coding styles?

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig#299]
Do we need a page to show snippets of EditorConfig files for popular coding styles? If so, how should we do it?

The 3 options are:

1. we do not need it
2. we need it, by creating a web page and accepting PR for it
3. we need it, by creating a wiki page that everyone can edit

Detailed discussion at #298 . This is voting only.

The voting will be closed before Apr 5th 11:59 UTC-12, if less than half of the members have voted at that time.

**Comment by sindresorhus** [comment]
2

**Comment by florianb** [comment]
2

**Comment by ffes** [comment]
2

**Comment by johan** [comment]
2

**Comment by jedmao** [comment]
2

**Comment by deinok** [comment]
2

**Comment by treyhunner** [comment]
2

**Comment by xuhdev** [comment]
2 wins
