### ISSUE TITLE
git submodule compatibility

### ISSUE THREAD

**Issue by jayce-leathers** [editorconfig/editorconfig#306]
I've been searching for answers on this with no luck so asking here to get a definite answer.

I have a git repo (call it Repo A) with a .editorconfig file in its root with `root = true` set in the file.

If I import Repo A as a git submodule in Repo B and also define a .editorconfig file in the root of Repo B with `root = true` will this cause issues? Will the .editorconfig within Repo A correctly have priority within Repo A?

Thanks ahead of time for any help!

**Comment by xuhdev** [comment]
There shouldn't be any issue. The `root = true` option is designed to handle this case: No `.editorconfig` file beyond that directory should be applied to any file in the directory.

**Comment by jayce-leathers** [comment]
Just a quick follow up if I were to symlink the .editorconfig from Repo A to Repo B would that cause any problems?

**Comment by xuhdev** [comment]
That would cause repo B to follow that `.editorconfig` file as well. What's the scenario you have for that?
