### ISSUE TITLE
New option proposal: syntax

### ISSUE THREAD

**Issue by ThiefMaster** [editorconfig/editorconfig#307]
Example usage:

```ini
[app.cfg]
syntax=python
```

This would tell the editor that this file contains Python code and should be highlighted, syntax-checked, etc. as if it was a regular python file.

Since languages name might be ambiguous (c#/csharp, html/html5, js/javascript) it would probably be a good idea to either provide a list of common names or expect editors implementing this to include common synonyms (e.g. js for javascript).

Another option could be not using a language name but a file extension/pattern. Editors usually associate languages based on file extensions (or rather file name patterns) so `[app.cfg] syntax=js` could tell the editor to apply the highlighting/formatting/... rules it would apply to an `app.cfg.js` file (or `app.js`?)

**Comment by xuhdev** [comment]
Duplicated #190 .
