### ISSUE TITLE
Global and filetype specific rules with recursive editorconfigs

### ISSUE THREAD

**Issue by mstruebing** [editorconfig/editorconfig#311]
I'm not sure what should happen in the following scenario:

Say I have a file `project/src/justSomeFile.md`
And one editorconfig in the root: `project/.editorconfig` with the following settings:

```ini
root = true

[*.md]
trim_trailing_whitespace = false
```

And an additional editorconfig in `project/src/.editorconfig` with the settings:

```ini
[*]
trim_trailing_whitespace = true
```

Which setting should be applied on the md file?

**Comment by xuhdev** [comment]
The one that comes later. In this case, `project/src/.editorconfig`.

**Comment by mstruebing** [comment]
So just to be clear:
It will not go up the directory tree and use the root .editorconfig because the `[*]` already machtes on every file, but when I would have no global rule(no `[*]`) in it it will go up the directory tree until it finds something?
Or will it just use the first editorconfig it finds regardless if there are more up the tree?

**Comment by xuhdev** [comment]
EditorConfig read `.editorconfig` files from higher level directories (won't go beyond `root=true`) to lower levels. In each file, it reads from top to the bottom.

In this case, it counters `[*.md]` section first and sees the match, and set `trim_trailing_whitespace=false`. Then, it counters `[*]` and sees the match again, and overrides `trim_trailing_whitespace=true`.
