### ISSUE TITLE
Cursor position is reset to the center of the line while typing

### ISSUE THREAD

**Issue by jpvantuyl** [editorconfig/editorconfig#319]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cake-vscode|cak|0.8.0
vscode-markdownlint|Dav|0.10.0
githistory|don|0.2.2
vscode-html-css|ecm|0.1.7
EditorConfig|Edi|0.9.4
gc-excelviewer|Gra|1.1.15
Ionide-fsharp|Ion|2.28.0
Go|luk|0.6.63
mssql|ms-|1.1.0
csharp|ms-|1.11.0
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.1.6
vscode-docker|Pet|0.0.16
java|red|0.7.0
code-settings-sync|Sha|2.8.2
code-spell-checker|str|1.3.2
vscode-react-native|vsm|0.4.0

---

Steps to Reproduce:

1. Ensure that an editor config file does not exist.
2. Open a document of any type (e.g. Readme.md)
3. Type furiously.  Just mash on the keyboard.  Or better yet, type "The quick brown fox jumped over the lazy dog"
4. Observe that the insertion point/cursor is not at the end of the line.  You just typed gibberish.  In the screencap below, the "he" from "the" has been moved to the end of the line.

![image](https://user-images.githubusercontent.com/1139835/28729953-2bda1bae-7383-11e7-9c15-c9ce5d7dd4b8.png)

Disabling the editorconfig extension resolves the issue.

Reproduces without extensions: No

**Comment by xuhdev** [comment]
Can you please report this bug [here](https://github.com/editorconfig/editorconfig-vscode/issues)?

**Comment by jpvantuyl** [comment]
Created it [there](https://github.com/editorconfig/editorconfig-vscode/issues/165).
