### ISSUE TITLE
Allow unlimited `max_line_length`

### ISSUE THREAD

**Issue by terrycloth** [editorconfig/editorconfig#321]
Some projects like having short lines for documentation, while some like longer lines. As I mentioned in #280, I'm told by an upstream that I'm contributing to that Doxygen works better with longer lines(?), so they do not hard-wrap their paragraphs at all.

Emacs and Atom, at least, use the `max_line_length` property to set the line length for their automatic paragraph reformatting features. For projects which do not hard-wrap lines of prose, it would be helpful if EditorConfig supported unlimited line lengths. At first I'd guessed that I should set the `max_line_length` property to `unset` or `off`, but those restore the editor's/user's default preference. So I guess what we need is an `unlimited` value.

**Comment by xuhdev** [comment]
What if you set it to be `999999`? Would it fit your requirement?

**Comment by terrycloth** [comment]
Oh, that's clever. I'm sure we're never going to write paragraphs longer than 999,999 characters, so I guess that works 😜 

I'd originally thought of adding an `infinity` value because I figured editor performance would be better if auto wrapping were actually *disabled* --- but when I tried `999999`, I didn't notice any difference in Emacs at least.

**Comment by xuhdev** [comment]
Great! I'm gonna close this issue.
