### ISSUE TITLE
add Kate and KDevelop to website

### ISSUE THREAD

**Issue by lydiapintscher** [editorconfig/editorconfig#322]
KDE's [Kate](https://kate-editor.org) and [KDevelop](https://www.kdevelop.org) do have support for editorconfig now. See [this thread](https://marc.info/?t=150204991100001&r=1&w=2) for some more details. It'd be great if you could add them to your website.

**Comment by xuhdev** [comment]
@ineptcat Can you help out again? Thank you!

**Comment by LeSpocky** [comment]
What about that?
https://github.com/editorconfig/editorconfig.github.com/issues/78

**Comment by xuhdev** [comment]
Sounds good. Let me close this.
