### ISSUE TITLE
Support HTTPS Scheme in Editorconfig.org Website

### ISSUE THREAD

**Issue by oboukli** [editorconfig/editorconfig#325]
Editorconfig.org website does not currently support the HTTPS scheme.

Usually, an `.editorconfig` file starts with a URL to editorconfig.org. For example:

```
# EditorConfig is awesome: http://EditorConfig.org
```

This URL may be problematic when using a lint tool, such as [DevSkim](https://github.com/Microsoft/DevSkim), which complains about the use of non-HTTPS URLs as a potential security issue.

I suggest adding support for HTTPS. A certificate can be obtained from certificate authority such as [Let's Encrypt](https://letsencrypt.org/).

**Comment by ffes** [comment]
Already an open issue in the repo for the website. Closing this as a dup of https://github.com/editorconfig/editorconfig.github.com/issues/66
