### ISSUE TITLE
Support end_of_line = native

### ISSUE THREAD

**Issue by jedmao** [editorconfig/editorconfig#327]
This is a voting only thread – [EditorConfig members only please](https://github.com/orgs/editorconfig/people).

Discussion should be at #226 .

👍 or 👎 

Let's decide before Nov 1st GMT -12 23:59

### `native` - ensure OS-native line endings

```ini
[*]
end_of_line = native
```

**Comment by jedmao** [comment]
👍

**Comment by xuhdev** [comment]
We actually have a dedicated [voting tracker](https://github.com/editorconfig/editorconfig-vote/issues). Do you wanna move there?

**Comment by jedmao** [comment]
https://github.com/editorconfig/editorconfig-vote/issues/2
