### ISSUE TITLE
Projects using editorconfig removed/b0rked

### ISSUE THREAD

**Issue by waterkip** [editorconfig/editorconfig#328]
https://github.com/editorconfig/editorconfig/wiki/Projects-Using-EditorConfig/_history

The last two commits removed and changed the page making it useless. Not sure if it is intended or needs to be restored.

**Comment by ffes** [comment]
I think you are right that some damage has been done. Especially the commit messages of the last two commits are a bit worrying.

Not sure though how to recover the the right commit. I assume there must be a better way then just copy the content of the last good commit and paste that in the page again.

**Comment by xuhdev** [comment]
Thanks for the report. I have recovered the last normal page by cloning using Git and reset to an earlier revision.
