### ISSUE TITLE
Documentation on editorconfig website for charset options is to strict for the utf-8-bom recommendation

### ISSUE THREAD

**Issue by vbaderks** [editorconfig/editorconfig#333]
The documentation on the EditorConfig website list the 5 main options for charset:
latin1, utf-8, utf-8-bom, utf-16be or utf-16le

It then states that "Use of utf-8-bom is discouraged.", which is a link to a StackOverflow discussion:
https://stackoverflow.com/questions/2223882/whats-different-between-utf-8-and-utf-8-without-bom/2223926#2223926

It depends however on the type of file and platform if the guidance is correct. Certain types and platform should use utf-8, however some types and platforms should use utf-8-bom. 

One example when usage of utf-8-bom is required is C++ .cpp and .h files that are being compiled with Microsoft Visual Studio 2015 or newer. If these files don't have a utf-8 BOM the C++ compiler will interpret these files in the current code page of the environment that is currently active, see:
https://blogs.msdn.microsoft.com/vcblog/2016/02/22/new-options-for-managing-character-sets-in-the-microsoft-cc-compiler/

Given the cross platform and IDE neutral nature of EditorConfig, this guidance could be given in a less strict recommendation or no recommendation at all.

Note:

Visual Studio 2017 15.5 fixed an issue which would prevent using .editorconfig with the  utf-8-bom setting:
https://developercommunity.visualstudio.com/content/problem/100735/since-153-breakpoints-dont-work-when-the-charset-o.html

**Comment by xuhdev** [comment]
I would suggest to remove this recommendation. @editorconfig/developers Any opinions?

**Comment by ffes** [comment]
I personally never really understood why it was there. So I have no problem with that recommendation being removed.

**Comment by jedmao** [comment]
I agree. Let's get rid of it.

**Comment by Mpdreamz** [comment]
Agreed :+1:
