### ISSUE TITLE
Define which EOL should insert_final_newline use if end_of_line is not defined

### ISSUE THREAD

**Issue by ppalaga** [editorconfig/editorconfig#335]
Given that `file.txt` does not end with a newline and given that `insert_final_newline = true` is the only property applicable to `file.txt`, which end of line string should the processor take to insert at the end of `file.txt`?

Clearly, if the `end_of_line` property is defined for `file.txt`, the processor can take its value. But what should the processor do if `end_of_line` is undefined?

I can think of the following options:

(1) If `file.txt` contains any EOL, use the last one, otherwise do nothing (or at least warn that `end_of_line` should be defined)

(2) Do nothing (or at least warn that `end_of_line` should be defined)

(3) Use `\n` as a hard coded default.

I think (1) is the proper solution for most cases.

I think (3) is generally wrong, because there probably exist languages where `\n` is not allowed.

Any other ideas?

**Comment by xuhdev** [comment]
In my opinion, according to the basic principles of EditorConfig, as long as `end_of_line` is unspecified, we should use whatever the editor specifies (as if EditorConfig is not installed).

For point (1), since we could have mixed line endings for any new lines if `end_of_line` is undefined, we shouldn't impose such a rule if people don't specify `end_of_line`.

**Comment by ppalaga** [comment]
> In my opinion, according to the basic principles of EditorConfig, as long as end_of_line is unspecified, we should use whatever the editor specifies (as if EditorConfig is not installed).

For my particular case of being a part of a Maven build process, where there is no editor in game, this would probably mean to take the given platform's default EOL (`\r\n` on Windows and `\ņ` otherwise). Let this be the option (4).

> For point (1), since we could have mixed line endings for any new lines if end_of_line is undefined, we shouldn't impose such a rule if people don't specify end_of_line.

I still think rule (1) has a better chance to keep files consistent compared to the option (4) taking the platform's (or current editor's) default. 

With rule (1), if the file has mixed EOLs, the editorconfig processor will not make it worse. And if the given file has whatever particular EOL string on all existing lines, the editorconfig processor keeps it so.

**Comment by xuhdev** [comment]
I think, in your case, this is more like creating a new editor and try to decide the default. Imagine you create an editor. Would you use option (4) as the default setting? If you think option (1) is better as the default,  you can go ahead. But, if we write this into the EditorConfig specification, it may mess up with users' own editor preferences.

**Comment by ppalaga** [comment]
Thanks for your assistance @xuhdev. I think I'll go with (1)
