### ISSUE TITLE
Error: Incorrect Parameter

### ISSUE THREAD

**Issue by Luberen** [editorconfig/editorconfig#339]
How can I resolve the error "The parameter is incorrect. (Exception from HRESULT: 0x80070057(E_INVALIDARG))"?

I selected Add->.editorconfig file and this error message came out.

**Comment by xuhdev** [comment]
Which editor are you using? You can report this bug to the issue tracker of the corresponding editor.

**Comment by Luberen** [comment]
I'm using Visual Studio 2017.
