### ISSUE TITLE
Add support for Visual Studio "Enable full solution analysis"

### ISSUE THREAD

**Issue by Gav-Brown** [editorconfig/editorconfig#341]
In Visual Studio you can specify `Options\Text Editor\C#\Advanced\Enable full solution analysis`. With this on VS will run all its Code Style rules on all files in the solution whether they are open or not.

However, when using an .editorconfig file, instead of the VS Code Style rules they replace, the rules only get applied to the currently open files.

Could we add support for and respect this option?

This may be a VS issue rather than EditorConfig?

**Comment by ffes** [comment]
> This may be a VS issue rather than EditorConfig?

It sure sounds like that

**Comment by Gav-Brown** [comment]
@ffes Do you know if this should go on the [dotnet/roslyn](https://github.com/dotnet/roslyn) board?
