### ISSUE TITLE
Dead link to gitignore man page on the website editorconfig.org

### ISSUE THREAD

**Issue by selu** [editorconfig/editorconfig#342]
The link for _gitignore_ currently points to http://manpages.ubuntu.com/manpages/intrepid/man5/gitignore.5.html#contenttoc2 in the section _File Format Details_ on http://editorconfig.org/, which page does not exist anymore.
I'd change it to https://git-scm.com/docs/gitignore#_description instead of any manpage from Ubuntu.

**Comment by xuhdev** [comment]
Thanks!
