### ISSUE TITLE
Probably inconsistent choice pattern

### ISSUE THREAD

**Issue by denofevil** [editorconfig/editorconfig#346]
Please consider following example

```ini
[*.{xml,html}]
indent_size=2

[*.{xml}]
indent_size=2
```

The first pattern is treated like any file having `xml` or `html` extension. While the second one is treated as a file having `{xml}` extension. This behaviour is checked explicitly [in the test suite](https://github.com/editorconfig/editorconfig-core-test/blob/master/glob/CMakeLists.txt#L122).

This behaviour might be a little bit confusing, but I'm not sure. We've got this question in [IntelliJ tracker](https://youtrack.jetbrains.com/issue/WEB-31749).

**Comment by xuhdev** [comment]
Yes, `{xml}` is supposed to literally mean `{xml}`. This is actually common behavior among other popular software. For example, in Bash, if you have two files `x.a` and `y.b`, `ls *.{a,b}` prints both file names but `ls *.{a}` does not print file names.

**Comment by erikjohnsen6d** [comment]
I think your second link was mislinked. https://youtrack.jetbrains.com/issue/WEB-31749

**Comment by denofevil** [comment]
@xuhdev thanks for the update, I think that it works as expected.

@erikjohnsen6d sorry, you're right, fixed link in the original message.

**Comment by erikjohnsen6d** [comment]
@xuhdev That seems like odd functionality to me, especially since this used to work in the editorconfig files in IntelliJ. But if you want say `[*.{xml}]` is invalid, that's fine. We'll edit our files.

**Comment by xuhdev** [comment]
We basically followed the majority of the glob engines out there. This is not our invention, and I think technical people sort of expect this. But feel free to add a warning in this case.

**Comment by denofevil** [comment]
Thanks everyone, I'm closing this one
