### ISSUE TITLE
feature request: disable indexing

### ISSUE THREAD

**Issue by landsman** [editorconfig/editorconfig#350]
Hi,

I am using PhpStorm with Drupal project contains large data folders and I want disable indexing these folders by `.editorconfig`. Could be that possible?

Thanks

**Comment by ppalaga** [comment]
I do not think EditorConfig project can help you. However you may try your luck asking under https://github.com/JetBrains/intellij-community or maybe @denofevil directly.

**Comment by xuhdev** [comment]
I agree with @ppalaga . This is likely to be out of the scope.

**Comment by denofevil** [comment]
Hey @landsman,

If these directories are specific for your project you can exclude them via Right click on a folder | Mark Directory as | Excluded and commit .idea/*.iml to the repository.

If these directories are commonly excluded across all Drupal project, please file an issue at https://youtrack.jetbrains.com/issues/WI

**Comment by Eaintmyatc** [comment]
![Uploading share_2024-10-20_04_00_07_716.png…]()
