### ISSUE TITLE
Add ReSharper / Rider in No Plugin editor

### ISSUE THREAD

**Issue by van800** [editorconfig/editorconfig#352]
editorconfig.org website has a list of "No Plugin" editors.

ReSharper has built-in support for editorconfig. https://www.jetbrains.com/help/resharper/Using_EditorConfig.html

Rider has support via bundled plugin.
https://www.jetbrains.com/help/rider/Using_EditorConfig.html

Please add.

**Comment by treyhunner** [comment]
I'm not sure whether ReSharper should go in the "No Plugin" section or somewhere else, since it's an extension for Visual Studio.

Regardless, logos for these on the website would be great. @Pittan would you have any interest in drawing a logo for these two soon?

**Comment by Pittan** [comment]
Sorry to be late :bow:  
Incoming ReSharper and Rider logos... 🚀
