### ISSUE TITLE
Cannot find the specification anywhere

### ISSUE THREAD

**Issue by kkm000** [editorconfig/editorconfig#360]
I am probably not seeing something obvious, but I cannot find the spec for `.editorconfig` format. I read the whole wiki of this repository. The website https://editorconfig.org/#file-format-details has one simple example, and a very terse description. The tests in https://github.com/editorconfig/editorconfig-core-test I cannot grok, there seems to be no expected result, only a source tree with files.

The question that I tried to figure out is the pattern precedence. Here's my practical issue, I want `trim_trailing_whitespace` be set to true for all files but `*.md`, where the EOL whitespace is significant. Should I just try to come up with a monstrosity like the following?
```ini
[**/*.{c,cc,cpp,h,txt,cs,res,rc,.... you got the idea]
trim_trailing_whitespace = true
[**/*.md]
trim_trailing_whitespace = false
```
The explanation has it that files *deeper in the tree* override those closer to the root, but says nothing about precedence of patterns in a single file. Is there a defined rule for that, what happens if I have 
```ini
[**/*]
trim_trailing_whitespace = true
[**/*.md]
trim_trailing_whitespace = false
```
Is this undefined? Will the last one win? Is it because it is latter in file, or because it is more specific? Or should I put the default before any pattern, where the `root` line is? The web site lisrs `root` among other properties, but the Wiki here says `root` is special and can be placed outside of patterns. The only example on editorconfig.org is careful to avoid such an ambiguity. For the life of me, cannot find this information. Should be totally by fault, as the project is 5 years mature and must have a lot of writeup published somewhere, but no searches turned up anything clarifying that. Can you please help?

**Comment by xuhdev** [comment]
Thanks for your report. The file format details on the webpage should describe all rules, while [here](http://docs.editorconfig.org/en/master/editorconfig-format.html) there are a more detailed details. If any rules that are unsaid but they are actually in the test, it's a documentation bug. Your question is answered in the other link, but not on the homepage. I will fix this on the homepage.

**Comment by dail8859** [comment]
My opinion...the current documentation is fine for *users*, however it is **severely lacking** for *developers* that want to implement their own core. I tried to do this in the past with Qt. To meet specification on the website is easy...to make it pass all the EditorConfig tests is non-trivial as there are numerous corner cases and ambiguities.

**Comment by xuhdev** [comment]
@dail8859 I understand that. Most corner cases belong to the specification of glob, which we borrowed as part of our specification. We only point out the difference between our format and glob -- and this is why the specification is short. Does this make sense? If you feel it is in a different case, please point out some exceptions and we'll make them clear...

**Comment by jedmao** [comment]
In response to your examples provided above, I think what you want is:
```ini
root = true

[*]
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false
```

The more specific rules trump the less specific. I'm also a bit unsure about the intent behind the order though. I'm not sure that we have any tests that test the order of these two rules against each other, but I do know that if you keep the more specific rules towards the bottom that it will definitely work the way you intend.

I realize that's not exactly what you want to hear, but I'm just trying to help. We could probably improve some things here.

**Comment by kkm000** [comment]
@jedmao, this statement contradicts the documentation that @xuhdev has pointed me to:

> Files are read top to bottom and the most recent rules found take precedence

(To clarify, I read "found" as "matching the filename to the rule's pattern".) In the example that you are providing, there is no difference, since the more specific rule `*.md` is also the most recent. However, in the case of 
```
[*.md]
trim_trailing_whitespace = false

[*]
trim_trailing_whitespace = true
```
the documentation suggests that `trim_trailing_whitespace = true`, being the most recent rule, will apply to all files, including `*.md`.

Which of the two statements is true? I am asking just for clarification.

> I realize that's not exactly what you want to hear

Why, it does solve my problem, thanks! Also, it is always possible to sort more specific rule groups toward the end of file (since "more specific" is a strict partial order relation).

**Comment by kkm000** [comment]
@xuhdev, thanks for the link to documentation. I could not find it, and it does answer the question!

**Comment by cxw42** [comment]
@kkm000 

> The tests in https://github.com/editorconfig/editorconfig-core-test I cannot grok, there seems to be no expected result, only a source tree with files.

I was confused by that as well.  Turns out the expected results are regexes in the `CMakeLists.txt` files in each directory.  E.g., [here](https://github.com/editorconfig/editorconfig-core-test/blob/master/cli/CMakeLists.txt#L44).

**Comment by kkm000** [comment]
@cxw42 Thanks for the pointer!

**Comment by craigbarnes** [comment]
> The more specific rules trump the less specific

@jedmao Are you sure about that? I'm pretty sure that's not the case for editorconfig-core-c.

**Comment by xuhdev** [comment]
@craigbarnes I think @jedmao only meant so in that specific example.

**Comment by jedmao** [comment]
If there is still confusion please post an example with expectations so we don't lose context.

**Comment by xuhdev** [comment]
This repo will hold the source of the specification: https://github.com/editorconfig/specification

**Comment by cxw42** [comment]
I just found this wiki page which is quite out of date :) --- https://github.com/editorconfig/editorconfig/wiki/File-Format-Change-Log

**Comment by cxw42** [comment]
All, now that the spec is at https://editorconfig-specification.readthedocs.io/en/latest/ , can this issue be closed?  I think the last remaining meta-issue is #398, currently out for a vote at editorconfig/editorconfig-vote#7.

**Comment by ffes** [comment]
In general you are right, but as far as I could see the specifications are not yet mentioned on the website. This issue is about finding the specs, so I would suggest to close this one when the website is updated.

And maybe the description of `.editorconfig` at the website could be simplified to a basic sample with explanation and a link to the specs. Also the wiki should be updated as well.

**Comment by cxw42** [comment]
@xuhdev I see the spec is now on https://spec.editorconfig.org as well --- is that the reference site going forward?

**Comment by xuhdev** [comment]
@cxw42 Yes, it is
