### ISSUE TITLE
An official format specification

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig#361]
@editorconfig/developers  @editorconfig/board-member  Should we mark the specification listed on the webpage as the official one? Right now they seem to be the de facto standard. Also see #360

**Comment by sindresorhus** [comment]
👍

**Comment by florianb** [comment]
👍

**Comment by jedmao** [comment]
👍

**Comment by johan** [comment]
👍

**Comment by Mpdreamz** [comment]
:+1:

**Comment by ffes** [comment]
:+1:

**Comment by treyhunner** [comment]
:+1:

**Comment by xuhdev** [comment]
For some reason, I completely forgot about this :flushed: I'll start a template soon. Closed now for completed voting. Additional comments please go to #360 .
