### ISSUE TITLE
CI Tests: check all files for compliance with .editorconfig rules

### ISSUE THREAD

**Issue by shoogle** [editorconfig/editorconfig#362]
Picture the following scenario:

- I run an open source project
- My project has a `.editorconfig` file
- My project has continuous integration tests on [Travis CI](https://travis-ci.org/) (or similar)
- The tests are run every time somebody submits a pull request to my project (and on every commit)

When contributors submit pull requests to my project, I'd like to check all changed files against the rules defined in `.editorconfig`. (This would be a kind of "sanity check" before the main tests are run.)

- I want the CI test to fail if somebody submits code that violates the rules in `.editorconfig`.
- The test will print a list of files that failed, and why each file failed.
- The test would inform contributors that they can visit https://editorconfig.org/ for instructions on how to setup their preferred editor/IDE so that their code will pass the test automatically.

Example output of test program:

```
./editorconfig-sanity-check: checking code files against rules in .editorconfig

README.md - Line 17 - trailing whitespace detected (trim_trailing_whitespace = TRUE)
docs/index.html - Line 4 - character 33 is invalid (charset = UTF-8)
src/module.py - Line 62 - indentation TAB detected (indent_style = SPACE)
src/module.py - Line 62 - wrong indent_size detected (indent_size = 4)
platform/script.sh - Line 28 - missing final newline (insert_final_newline = true)
platform/script.bat - Line 1 - wrong line ending detected (end_of_line = CRLF)

For instructions on how to setup your editor/IDE to avoid making these errors
in the future, please see <https://editorconfig.org/>.
```

As you can see, providing this feature is a win for both maintainers and contributors, and provides a lot of free publicity for EditorConfig!

**Comment by xuhdev** [comment]
There are already several (sub-)projects on this. See the [FAQ](https://github.com/editorconfig/editorconfig/wiki/FAQ#my-files-are-not-automatically-reformatted-the-editorconfig-plugin-is-not-working).

**Comment by shoogle** [comment]
Thanks. The list was a bit hidden so I updated the FAQ to make it easier to find.

**Comment by xuhdev** [comment]
Thanks, closing now.
