### ISSUE TITLE
Match pattern [*] not match dotfiles

### ISSUE THREAD

**Issue by xorcare** [editorconfig/editorconfig#374]
Why the pattern [*] does not work for files:
 - .gitignore
 - .editorconfig
 - .gitattributes

We have to use the pattern [{.* ,*}] is this normal behavior?

IDE: Goland, PHPStorm, WebStorm

**Comment by xuhdev** [comment]
They should work for dotfiles. The IDEs you list, however, are not maintained by us. They are directly maintained by JetBrains. Can you report to [their bug tracker](https://youtrack.jetbrains.com/issues/TW)? We will add a test case to cover this case.

**Comment by ppalaga** [comment]
I have sent a PR https://github.com/editorconfig/editorconfig-core-test/pull/21 to add some tests for this to the core test suite. Our ec4j-core parser is passing those tests FWIW.

@xorcare I think the IDEs you listed use https://github.com/editorconfig/editorconfig-core-java by @denofevil . You may want try your luck there.

**Comment by xuhdev** [comment]
The test has been added by @ppalaga : editorconfig/editorconfig-core-test@6ea1d8ece62cac9cf72c79dce4879b046abe1fe7

**Comment by xorcare** [comment]
The pattern `[*]` works on linux and doesn't work on Mac OS until the problem is resolved.

**Comment by xuhdev** [comment]
@xorcare Are you using two different implementations? You can test this by running `editorconfig --version`.

**Comment by xorcare** [comment]
Now everything works normally, maybe I did not understand something, and maybe the idea update helped.
