### ISSUE TITLE
Test suite: Permit editorconfig programs to provide correct output lines in any order

### ISSUE THREAD

**Issue by cxw42** [editorconfig/editorconfig#375]
At least the lowercase-value tests beginning [here](https://github.com/editorconfig/editorconfig-core-test/blob/516f86921a2e3c5e8e6196bf2c4ab76d0fb6e878/properties/CMakeLists.txt#L58) check for two or more lines of output in succession using `^(line1)(line2)$` (in essence).  This requires that `line1` and `line2` be output in that order.  ([CMake regex reference](https://cmake.org/cmake/help/latest/command/string.html#regex-specification))

However, I cannot find any documentation here, in the [editorconfig-core-test issues](https://github.com/editorconfig/editorconfig-core-test/issues), in #22 , on https://editorconfig.org, or in the [Doxygen output](http://docs.editorconfig.org/en/master/editorconfig.html), that specifies that requirement.  

As far as I can tell, the test requires the options be output in the same order they are given in [the .editorconfig file](https://github.com/editorconfig/editorconfig-core-test/blob/516f86921a2e3c5e8e6196bf2c4ab76d0fb6e878/properties/lowercase_values.in).  Is that indeed a requirement?  It seems somewhat brittle to me.

Would it be possible to change the spec and tests so that the output lines from the `editorconfig` program can appear in any order?

**Edit**

Adding both orders to the test case is a brute-force option, but it works.  For example:

    new_ec_test(lowercase_values1 lowercase_values.in test1.c
        "(^indent_style=space[ \t]*[\n\r]+end_of_line=crlf[ \t\n\r]*$)|(^end_of_line=crlf[ \t\n\r]+indent_style=space[ \t]*[\n\r]*$)"
        )                                                            #^ the part starting here is new

**Edit 2** The linked commit is a better way to fix it, in my opinion - test for each line with a separate regex.

**Comment by xuhdev** [comment]
You are right they shouldn't be required. IMO this is indeed a bug in the test suite.

**Comment by cxw42** [comment]
Thanks!  I'll finish working through the tests and then submit a PR in editorconfig-core-test, unless you have a different preference.

**Comment by xuhdev** [comment]
@cxw42 Thanks! Shall we give it a few days in case I may miss something? @editorconfig/developers am I right that currently no one is using the specific order of output by EditorConfig cores? Once the test cases change, we will loose the output by allowing different orderings of property value pairs.

**Comment by ppalaga** [comment]
I am not against the core idea of this proposal - i.e. to change the tests in such a way that the order in the returned set of properties is not significant. At the same time, I am against how the proposal is implemented in https://github.com/cxw42/editorconfig-core-test/commit/99187fc4b6892c40cbff87758b3227f7b21db6ec . The strategy used there, namely

> Any time you want to test for two different output lines, test them separately.

Substantially changes the semantics of the tests. Before the change, the returned results are often combined from multiple sections. After the tests the combination is not there and the combination logic in the tested editorconfig processors is not executed.

Please find a different way how to reach your goal.

**Comment by xuhdev** [comment]
I think @ppalaga 's comments make sense. In particular, you can modify [new_ec_test](https://github.com/editorconfig/editorconfig-core-test/blob/master/CMakeLists.txt#L42) to easily alter test cases.

**Comment by cxw42** [comment]
@ppalaga Thanks for your feedback!  I am not sure I quite understand.  Would you please look at new commit [c82e1ab](https://github.com/cxw42/editorconfig-core-test/commit/c82e1ab90ef30ea19b2d927672a8e91ebe02fba3) and see if it covers the case you are thinking of?  For a target of `test.file`, it checks that `[test.*]` and `[*.file]` properties have been combined, but does so with a test per output line.  If that commit indeed covers the situation you are concerned about, would you please give me a bit more detail about the failure mode that [c82e1ab](https://github.com/cxw42/editorconfig-core-test/commit/c82e1ab90ef30ea19b2d927672a8e91ebe02fba3) would not detect, but that the current tests would detect?

I agree that for tests of multiple files in one run (INI-format `editorconfig` output), a test per output line is insufficient.  It might be worth narrowing the scope of this issue to tests of only one file.

I also agree that a test per output line is insufficient if an `editorconfig` command, when run twice with the same inputs, produces different outputs.  However, I submit that any core implementation with that problem will likely fail more than just these tests :) .

That said, we can use the brute-force approach of `(<order 1>|<order 2>|...|<order n>)`.  However, that requires the test author to copy and edit the same regex `n!` times.  I am concerned about the readability of such a test.  Plus, people writing new tests might accidentally introduce typos while changing the order.

Currently, editorconfig-core-test requires CMake 2.6+ (according to its CMakeLists.txt).  If we could bump that up to 3.0+, we would have more string- and list-manipulation support.  With 3.0+, we might be able to generate all the different orders programmatically, which would remove the typo risk.  We would just have to be careful about semicolons (CMake list separators), which I don't think would be an issue.

What say you all?

**Comment by cxw42** [comment]
@ppalaga I'll bump to 3.0 and see about auto-generating the factorial combination.

@xuhdev It will definitely take me a little while to work on this :) .  I will reply again when I have something ready for everyone's review.

**Comment by cxw42** [comment]
@ppalaga Two things that just occurred to me before I go off and write code that will generate 120 permutations in one test to replace the five tests in c82e1ab.  

So that I understand where you're coming from, is your objection philosophical or based on a failure case you've seen before?  I'd still be interested to see an incorrect core that passes under test-per-line (other than a core deliberately written to output individual lines in the order expected by the tests!).

### 1

Would you be comfortable with the one-line-per-test approach if we _also_ tested against the expected number of lines of output?  For example, if editorconfig should output

    a=1
    b=2

then use three tests:

 - `(^|[\n\r]+)a=1[ \t\n\r]+`
 - `(^|[\n\r]+)b=2[ \t\n\r]+`
- (new one) `^[^=]+=[^=]+=[^=]+$`

That is, test that there are exactly two lines of output (the new one; keys off the `=` chars), and that the two lines that we want both appear.  

### 2

In CMake 3.0.2+, we can use [`execute_process()`](https://cmake.org/cmake/help/v3.0/command/execute_process.html) to capture stdout.  With a nested cmake or ctest invocation, maybe we could capture that output and then test multiple regexes against the single captured output.

**Comment by hgraeber** [comment]
Hi Peter!

Am 2018-10-19 um 10:24 schrieb Peter Palaga:
> [...]
>
> I hope for something like
>
> |new_ec_test(star_matches_dot_file_after_slash star.in
> Bar/.editorconfig any_order("keyb=valueb", "keyc=valuec")) |
>
> instead of the current
>
> |new_ec_test(star_matches_dot_file_after_slash star.in
> Bar/.editorconfig "^keyb=valueb[ \t\n\r]*keyc=valuec[ \t\n\r]*$") |
>
> I have no idea whether this is possible with the cmake scripting.
>
No, It's not. But cmake parameter lists can have arbitary length:

|new_ec_test(star_matches_dot_file_after_slash star.in Bar/.editorconfig
"^keyb=valueb[ \t\n\r]*$" "^keyc=valuec[ \t\n\r]*$")|

Adittionally it is possible to have self-defined keywords in the
parameter list, something like named parameters. Those or by convention
completely uppercase. This may look like

|new_ec_test(star_matches_dot_file_after_slash star.in Bar/.editorconfig
REGEXP "^keyb=valueb|||[ \t\n\r]*$|" "^keyc=valuec||||[ \t\n\r]*$|| "))|

The keyword is not really needed, but its use makes it easier to extend
the parameter list of|new_ec_test |further if necessary. For example for
full matches without regexp for easy cases:

|new_ec_test(star_matches_dot_file_after_slash star.in Bar/.editorconfig
MATCH "keyb=valueb||||" "keyc=valuec"||))|

Maybe it is useful to add other keywords, too:

|new_ec_test(TEST star_matches_dot_file_after_slash FILE star.in
EDITORCONFIG_FILE Bar/.editorconfig MATCH "keyb=valueb||||" "keyc=valuec"||))|

Herbert

**Comment by cxw42** [comment]
@ppalaga Thanks for the explanation!  I understand communication challenges, and why those challenges cause you to prefer keeping the existing structure.  I am almost done with a core in native VimScript (to replace the current Vim plugin+Py core), so the number of projects to communicate among will be even higher in the near future :) .  

@hgraeber Thanks for pointing out those options!  I will start with the simple case (arbitrary number of regexes) and see about more flexible argument handling later if appropriate based on feedback.

**Comment by cxw42** [comment]
All, my next take is in the [anyorder branch](https://github.com/cxw42/editorconfig-core-test/tree/anyorder).  On Cygwin, the C core and my Vimscript core* pass all the tests in this branch.  Here's the [comparison](https://github.com/editorconfig/editorconfig-core-test/compare/master...cxw42:anyorder).  In short:

 - New test function `ec_test_lines()` sets up a test that will match the given regex lines in any order.  Example call:

       ec_test_lines(NAME parent_and_current_dir 
                     EC_FILE parent_directory.in 
                     SRC_FILE parent_directory/test.b
                     REGEXES "key1=value1[ \t]*" "key2=value2[ \t]*")

   looks for a `key1=value` lines followed by a `key2=value2` line, or vice versa.

 - Helper file [`cmake/multiline_matcher.cmake`](https://github.com/cxw42/editorconfig-core-test/blob/anyorder/cmake/multiline_matcher.cmake) defines function `make_regex_of_permutations()` that generates a single regex of all the permutations.

Shall I submit a PR now and move the discussion there, or would you prefer to continue on this thread?  Also, I can squash before submitting the PR if you wish, or you can squash later.

**Note:** I decided to require CMake 3.**1**.0 instead of CMake 3.0.0.  This is because 3.1.0 introduces the sane argument handling in `if()` conditionals.  I don't feel like enough of a CMake expert to avoid subtle bugs in conditionals under the old rules.  @ppalaga, as you [mentioned earlier](https://github.com/editorconfig/editorconfig/issues/375#issuecomment-431036167), CI is at least 3.9.x, so I don't think this should be a problem. 

Thanks!

* Except that the Vimscript core doesn't yet support the single UTF-8 test, and doesn't run the tests of the behaviour noted in #371.

**Comment by ppalaga** [comment]
>   ```
>   ec_test_lines(NAME parent_and_current_dir 
>                 EC_FILE parent_directory.in 
>                 SRC_FILE parent_directory/test.b
>                 REGEXES "key1=value1[ \t]*" "key2=value2[ \t]*")
>   ```

Thanks, I like this. Just maybe replace `REGEXES` with `EXPECTED`.

**Comment by ppalaga** [comment]
> the current version is limited to three

Assuming there is no test in the suite nowadays working with more than three lines, what happens when more than three expressions are `EXPECTED`? I do not mind the limitation, if the test execution fails with a clear message in such cases.

**Comment by cxw42** [comment]
@ppalaga Yep, it dies with a very blatant error message :) .  See [here](https://github.com/cxw42/editorconfig-core-test/blob/017f426d45a533e1f3e25e85dd0f1ded53432617/cmake/multiline_matcher.cmake#L268).

I'll squash and open a PR in the next day or two.

**Comment by cxw42** [comment]
All, PR editorconfig/editorconfig-core-test#22 is open for your consideration.  Thanks!

**Comment by cxw42** [comment]
@xuhdev editorconfig/editorconfig-core-test#22 is ready for merging per @ppalaga.  It looks like you are the most common committer in that repo - what's the procedure?  Thanks!
