### ISSUE TITLE
How does .editorconfig lookup work and how does it play together with root = true

### ISSUE THREAD

**Issue by FSMaxB-divae** [editorconfig/editorconfig#376]
I couldn't find any specification on how the `.editorconfig` files are applied.

My current understanding for any given file:
1. look for a `.editorconfig` in the current directory and apply all the properties
2. If `root = true`, stop
3. go up in the parent directory and apply all properties that haven't been set already.
4. Continue with 2.

One specific question I have is the following:
If I want to ignore a subdirectory, is it sufficient to put a `.editorconfig` with just `root = true` in it?
The only other idea I can come up with is to create a `.editorconfig` in that subdirectory that sets every property to `unset`.

**Comment by xuhdev** [comment]
See the "Where are these files stored?" on the homepage:

> When opening a file, EditorConfig plugins look for a file named .editorconfig in the directory of the opened file and in every parent directory. A search for .editorconfig files will stop if the root filepath is reached or an EditorConfig file with root=true is found.

> EditorConfig files are read top to bottom and the most recent rules found take precedence. Properties from matching EditorConfig sections are applied in the order they were read, so properties in closer files take precedence.

The answer to your section question is yes.

**Comment by FSMaxB-divae** [comment]
I see, thanks for your answer. Now I feel kind of stupid for missing that section on the home page.

**Comment by kokolerk** [comment]
sorry, I now face the same questions. I wonder whether to actually write "root=true" in the .editorconfig file?

**Comment by EFEaglehouse** [comment]
> I see, thanks for your answer. Now I feel kind of stupid for missing that section on the home page.

I saw nothing there. When I go to the Home page on the Wiki, it's completely blank.

**Comment by florianb** [comment]
@EFEaglehouse you can find it on the homepage: https://editorconfig.org/#file-location

@kokolerk you use `root = true` to avoid editorconfig traversing up to the file system root (`c:` oder `/`) - usually that's used in "per project" configs to avoid that local editorconfigs of the single developer are being used at all.
