### ISSUE TITLE
Missing 64bit Notepad++ plugin release

### ISSUE THREAD

**Issue by redtide** [editorconfig/editorconfig#377]
Installing the plugin (v0.3.1 from sourceforge.net) in npp results with a message "Cannot load 32-bit plugin" from the plugin manager: do we miss a 64bit release? I noticed also an unknown build status on the git repository.

**Comment by xuhdev** [comment]
Please refer to editorconfig/editorconfig-notepad-plus-plus#9 :)

**Comment by redtide** [comment]
> Please refer to [editorconfig/editorconfig-notepad-plus-plus#9](https://github.com/editorconfig/editorconfig-notepad-plus-plus/issues/9) :)

oops! Thank you! I think I did not pay enough attention to the search results while trying to see if the issue was already notified.
