### ISSUE TITLE
test: Why trim_trailing_whitespace=false for CMakeLists.txt?

### ISSUE THREAD

**Issue by cxw42** [editorconfig/editorconfig#380]
In editorconfig-core-test, the [`.editorconfig` file](https://github.com/editorconfig/editorconfig-core-test/blob/master/.editorconfig#L2) says:

    [CMakeLists.txt]
    trim_trailing_whitespace = false

Why?  Any objection to changing `false` to `true`?

The same file also says to keep trailing whitespace for `*.in`, which I understand.  The `*.in` files have to stay as they are in order to test handling of trailing whitespace in the input files.  However, in the CMakeLists.txt, any whitespace we care about should be captured in a double-quoted string.  Right? 
 Thanks!

**Comment by xuhdev** [comment]
I think this was probably done by mistake. If you use `git blame` to check the commit message, it says:

>  Don't trim trailing whitespace in test files.

CMakeLists.txts are not test files.

**Comment by cxw42** [comment]
Thanks!
