### ISSUE TITLE
Please add @ppalaga to the board

### ISSUE THREAD

**Issue by ppalaga** [editorconfig/editorconfig#382]
@xuhdev [asked](https://github.com/editorconfig/editorconfig/issues/378#issuecomment-440022934) if I am interested in joining the board. Thanks for the trust, I am :). 

About me:

* Co-author of [ec4j](https://github.com/ec4j/ec4j) EditorConfig parser/evaluator written in Java.
* Author of [editorconfig-maven-plugin](https://github.com/ec4j/editorconfig-maven-plugin), [editorconfig-gradle-plugin](https://github.com/ec4j/editorconfig-gradle-plugin) and [editorconfig-ant-tasks](https://github.com/ec4j/editorconfig-ant-tasks) which are all plugins for the respective Java Build tools which can check whether project files comply with format rules defined in .editorconfig files and eventually also for fixing the violations
* I am currently working on a set of EditorConfig properties for formatting Java files - see https://github.com/editorconfig/editorconfig/issues/381
* I contributed a few fixes to [editorconfig-core-test](https://github.com/editorconfig/editorconfig-core-test/commits?author=ppalaga)
* All of the above are my private activities

**Comment by xuhdev** [comment]
I just initiated a voting editorconfig/editorconfig-vote#3

**Comment by cxw42** [comment]
This can be closed, right?

**Comment by xuhdev** [comment]
RIght. Thanks!
