### ISSUE TITLE
Should we continue having specification related issues in this repo or in editorconfig/specification?

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig#398]
Now we have a new repo editorconfig/specification, which hosts the files for generating a page describing specification. For future requests of changes in specification, should we continue using this repo, or switch to editorconfig/specification? In other words, should editorconfig/specification be kept for the specification website related issues only, or be used for the content of specification as well?

**Comment by xuhdev** [comment]
I think having new specification issues there is more neat, but would render a discontinuity of searching specification issues.

**Comment by cxw42** [comment]
I have thought about this some.  I would personally prefer keeping the substantive issues in this repo for easier searching.  However, I think that if the issues are still enabled on editorconfig/specification, people will probably open issues there anyway.  So I would suggest either keeping _all_ issues here, or moving substantive specification issues and website issues to editorconfig/specification.

**Comment by cxw42** [comment]
@xuhdev editorconfig/editorconfig-vote#7 does not appear to mention the option of using no issues at all in editorconfig/specification, and instead keeping all issues in editorconfig/editorconfig.

**Comment by xuhdev** [comment]
@cxw42 Normally when we establish a new repo, we use its issue tracker for it. We have this voting because there is an ambiguity in this convention for this particular new repo.

**Comment by cxw42** [comment]
@xuhdev Thanks for the clarification!

**Comment by ffes** [comment]
The wording of the vote is confusing. "Should we do A or B". Possible answer "yes" or "no".

**Comment by xuhdev** [comment]
@ffes I updated the wording. Nice catch!

**Comment by jedmao** [comment]
I think it's pretty confusing where to draw the line on whether to post an issue to this repo or the main one, so if we can't define that threshold well enough, I think closing the issue tracker here would be ideal, as it would remove confusion.

**Comment by cxw42** [comment]
Per https://github.com/editorconfig/editorconfig-vote/issues/7#issuecomment-541449994 , I think:

- this issue can be closed
- the remaining issues in editorconfig/specification can be moved to editorconfig/editorconfig
- the editorconfig/specification repo settings can be changed to disable the issue tracker there

Does that match everyone else's understanding?

**Comment by xuhdev** [comment]
Yes. I'm closing this now.
