### ISSUE TITLE
Question: How to deal with nested laguages like php in html?

### ISSUE THREAD

**Issue by rowild** [editorconfig/editorconfig#400]
WordPress seems to be the perfect example for that. PHP code in HTML code. HTML wants 2 intents, php 4 (according to PSR2).
Is there a way to define such a rule set in editorconfig?

**Comment by xuhdev** [comment]
There is likely no universal way to handle that for now. However, you can consider customized hook mechanism for [certain editors](https://github.com/editorconfig/editorconfig-emacs/blob/d073dd44c4813536dee6eadaf9e43f36ac0a3202/editorconfig.el#L116).

**Comment by rowild** [comment]
Thank you, @xuhdev ! I'll have a look!
