### ISSUE TITLE
Inline Javascript is not formated

### ISSUE THREAD

**Issue by daleqq** [editorconfig/editorconfig#402]
When format a HTML file with inline javascript in `<script>` tag, the HTML is formatted but the inline javascript is not formatted.

**Comment by cxw42** [comment]
Thanks for reporting!  This sounds like it is probably an editor-specific issue, and probably not specific to this project.  Which editor are you using?

**Comment by daleqq** [comment]
Thanks. I use Visual Studio 2017.

**Comment by cxw42** [comment]
Looks like VS2017 has known JS problems.  From a search, I found https://developercommunity.visualstudio.com/content/problem/141877/javascript-language-service-doesnt-work.html and https://github.com/microsoft/vscode/issues/16029 .  I am closing this issue as not related to EditorConfig.

The EditorConfig project does not manage all configuration settings for a code editor.  It primarily focuses on whitespace handling.  If you are having an EditorConfig problem, you will probably know it :) .  For general VS editor support, Microsoft sites are probably a better bet.  Good luck!
