### ISSUE TITLE
Cannot read property 'toString' of undefined in VS Code

### ISSUE THREAD

**Issue by jmtb28** [editorconfig/editorconfig#413]
OS: Debian 10
VS Code: 1.40.1
Extension: 0.14.2

How to replicate this bug:
1. Close all the editors
2. Press `Ctrl` + `Shift` + `P`
3. Type "Generate .editorconfig"
4. Press `Enter`

**Comment by xuhdev** [comment]
Could you move the issue here: https://github.com/editorconfig/editorconfig-vscode/issues ?

**Comment by jmtb28** [comment]
My bad. I went to the wrong repo.
