### ISSUE TITLE
Plans to write a rust version of the core?

### ISSUE THREAD

**Issue by mstruebing** [editorconfig/editorconfig#414]
Hey editorconfig-team,

I'm the maintainer of editorconfig-checker and plan to rewrite the core in rust maybe.
However, for that it would be great to have a rust version of the editorconfig-core available, which isn't currently there.

Do you plan to build such a thing? If so, how could I help to make this happen?

Thanks in advance!

**Comment by treyhunner** [comment]
@mstruebing replying very very late to say we don't have plans for that, but if you make your own Rust core, you'll want to run the official end-to-end tests against it the same way we do in the Python, C, and Java core libraries.

I'd guess an fnmatch-like Rust package and an INI-parsing Rust package are probably floating around out there in the wild in an almost-EditorConfig-ready state.

The hardest part will probably be getting the test suite setup in your repo and your code working against it (I've never found CMake easy).

If you do make an editorconfig-core-rust package, it'd be nice to link to it on the editorconfig.org website.

**Comment by mstruebing** [comment]
It took a long time but I'm starting to implement it: https://github.com/mstruebing/editorconfig-core-rust

**Comment by mstruebing** [comment]
I've made good progress today but I do not know how to make the core tests pass, I've tried to read them but it's hard for me to understand what's happening. If anyone could give some hints or PRs that would be nice!

**Comment by mstruebing** [comment]
https://github.com/editorconfig/editorconfig-core-test/issues/50

**Comment by florianb** [comment]
@mstruebing - we already worked on a ini parser in preparation for a Rust/WASM core of EditorConfig. It is more or less experimental yet. It may be useful for you: https://github.com/orgs/one-ini/repositories

**Comment by mstruebing** [comment]
I just found this repository: https://github.com/TheDaemoness/ec4rs/tree/main
So I guess this issue can be closed.
