### ISSUE TITLE
insert_final_newline = true and empty files

### ISSUE THREAD

**Issue by ppalaga** [editorconfig/editorconfig#416]
I wonder how an editorconfig processor should behave with `insert_final_newline = true` for an empty file? Should it (a) leave it as is or (b) should it add a line separator?

### Background

My [editorconfig-maven-plugin](https://github.com/ec4j/editorconfig-maven-plugin) currently requires the line delimiter even in empty files and I got a [user report](https://github.com/ec4j/editorconfig-maven-plugin/issues/43) claiming that the behavior is not compatible with some python tooling.

When searching for some editorconfig recommendations in this area, I just found a similar unresolved eclint issue https://github.com/jedmao/eclint/issues/156
So I guess there is no editorconfig-wide consensus about the matter.

### Solution proposal

I understand the `insert_final_newline` as a means for enforcing files to comply with the [POSIX definition of text file](https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xbd_chap03.html#tag_21_03_00_83) That definition explicitly says that it

> allows a file with a single <newline>, or a totally empty file, to be called a text file.

So I think it should be OK to let an editorconfig processor to leave an empty file as is even with `insert_final_newline = true`

WDYT?

**Comment by cxw42** [comment]
I agree that a zero-byte file does not need a newline added to it.

**Comment by randstr** [comment]
Definitely option a) leave it as is. It's the only sensible behavior IMO.

**Comment by ppalaga** [comment]
Thanks, I went with the option (a) - leave empty files as they are.
