### ISSUE TITLE
 Support excluding files from EditorConfig rules 

### ISSUE THREAD

**Issue by henrik242** [editorconfig/editorconfig#421]
I want to apply some rules for `*.js` files, but not for `*.min.js` files.  The following `.editorconfig` works:
```
[*.{js,jsx}]
max_line_length = 140
indent_size = 4
indent_style = space
charset = utf-8
insert_final_newline = true

[*{.min,.min.*,-min}.js]
max_line_length = off
indent_size = off
indent_style = off
charset = off
insert_final_newline = off
``` 

The `max_line_length = off`  line is [supported](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#max_line_length) but the other `off` statements are not.

1) Would you consider supporting `off` for the other rules as well?   I cannot see any reason why the others shouldn't.

2) Alternatively, is there another way of exclude `*.min.js` from the rules given to `*.js` in the .editorconfig file?

**Comment by cxw42** [comment]
Does `= default` (instead of `= off`) work for the other properties?

**Comment by henrik242** [comment]
Nope :( 

<img width="277" alt="Skjermbilde 2020-03-02 kl  17 44 42" src="https://user-images.githubusercontent.com/129931/75697836-ee941080-5cad-11ea-9704-cf0396d32ce3.png">

**Comment by cxw42** [comment]
Too bad!  Out of curiosity, which editor/checker are you using?  Is the `'default` not allowed here` message from the plugin or the core?

**Comment by henrik242** [comment]
This is IntelliJ IDEA. I guess the message is from the plugin, but I'm not sure.

**Comment by greut** [comment]
Isn't it `= unset`

**Comment by henrik242** [comment]
That works!  Thanks!

<img width="322" alt="Skjermbilde 2020-03-16 kl  13 06 54" src="https://user-images.githubusercontent.com/129931/76756972-088e2280-6787-11ea-9ff1-3e206f80caef.png">
