### ISSUE TITLE
Update Specification for `?`

### ISSUE THREAD

**Issue by dail8859** [editorconfig/editorconfig#424]
The specification for the [glob expressions](https://editorconfig-specification.readthedocs.io/en/latest/#glob-expressions) states:

> `?`     any single character

However, according to tests, the `?` should not match `/` characters:

https://github.com/editorconfig/editorconfig-core-test/blob/6c8fe6815b12f96f4b357d610ee1cd8da074880a/glob/CMakeLists.txt#L61-L62

**Comment by cxw42** [comment]
Thanks for catching that!  PRs welcome in editorconfig/specification :D .
