### ISSUE TITLE
Cannot turn off one rule for one package

### ISSUE THREAD

**Issue by VovaStelmashchuk** [editorconfig/editorconfig#427]
I want to disable one of my custom rules for one package.
My `.editconfig` 
```kotlin
[*.{kt, kts}]
disabled_rules = import-ordering, no-wildcard-imports, comment-spacing

[**/api/*.{kt, kts}]
disabled_rules = class-must-be-internal
```

Expected result: Files in package `api` can ignore rule `class-must-be-internal`.
Actual result: Linter apply rule `class-must-be-internal` for all files.

**Comment by cxw42** [comment]
Thanks for reporting!  What linter are you using?  Does your linter say it supports `disabled_rules`?

- If so, you need to talk to the people who make the linter.
- If not, are you asking for EditorConfig to add `disabled_rules` as a new supported key?  Even if we did, your linter would also have to implement that new key.

**Comment by VovaStelmashchuk** [comment]
Thx, for response. Sorry my bad.
