### ISSUE TITLE
Should empty .editorconfig files be considered valid?

### ISSUE THREAD

**Issue by ppalaga** [editorconfig/editorconfig#433]
ec4j currently fails with a parser error when processing an empty .editorconfig file - i.e. a file with zero length, but the same question holds for files containing only line breaks and comments. Should they be considered valid .editorconfig files defining zero rules?

**Comment by xuhdev** [comment]
I see nothing prevents empty .editorconfig from being valid.

**Comment by ppalaga** [comment]
> I see nothing prevents empty .editorconfig from being valid.

We should have a tests for such files then.

**Comment by ppalaga** [comment]
> We should have a tests for such files then.

Created https://github.com/editorconfig/editorconfig-core-test/pull/42
