### ISSUE TITLE
Specification doesn't include details about file location

### ISSUE THREAD

**Issue by rjmunro** [editorconfig/editorconfig#435]
The specification mentions that the file is called `.editorconfig` "by default", but doesn't mention that it should always be in the root of the project if you expect all editors to find it automatically.

It would be good if the spec could ask implementors to additionally check`.config/editorconfig` as discussed here:
https://github.com/nodejs/tooling/issues/79

**Comment by xuhdev** [comment]
Do you think the "File Processing" section has explained what you are asking for? https://editorconfig-specification.readthedocs.io/en/latest/#file-processing

**Comment by rjmunro** [comment]
Rereading, it does explain it yes. Sorry about that.
