### ISSUE TITLE
editorconfig logotype in SVG?

### ISSUE THREAD

**Issue by bromso** [editorconfig/editorconfig#438]
Can you please make your logo available in SVG format?

TIA

**Comment by ffes** [comment]
In #291 is a download available

**Comment by bromso** [comment]
@ffes Thanks!

Weird thou, I searched for logo, logotype, svg in issues but found nothing. Anyways, thanks again! :)

**Comment by xuhdev** [comment]
We probably should put the logo somewhere more visible though. But I'm struggling to see where the best place could be.

**Comment by bromso** [comment]
@xuhdev maybe just a folder in the repository named 'media' or 'assets'? I've looked around at technologies I use in my daily life, because I would like to market them more, and quite a few of those technologies solve this issue in that manner.
