### ISSUE TITLE
Feature request: specify or control Github editor vertical window size

### ISSUE THREAD

**Issue by signalogic** [editorconfig/editorconfig#442]
As 4K screens become more widely used in WFH offices, editing code in Github would be more productive if the editor window showed more lines or had a pull-down handle to control the height.  Currently with a 4K screen the Github editor leaves have the web page blank. I understand that Github is not intended for major editing, but at the same time when the editor comes up, it looks like it was created back in 1920x1080p days and hasn't been updated in 10+ years

**Comment by ffes** [comment]
How on earth can EditorConfig control how GitHub programs its software. Even if we should add a property that could control this, the people of GitHub still need to implement that in their software, And one can ask of this is a general thing for a codebase. This sounds more like a user setting in GitHub or a better detection on their site.

Maybe GitHub could add a custom property just like for instance [.NET does](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options), but that is entirely up to them.

I really don't see what EditoConfig has to do with this, so I'm closing this.
