### ISSUE TITLE
dead link: complete list of properties

### ISSUE THREAD

**Issue by anatawa12** [editorconfig/editorconfig#443]
at https://editorconfig.org/#supported-properties, there's the link to https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties but the wiki page does not exist.

**Comment by xuhdev** [comment]
Thanks, I recovered the wiki page. Looks like some spamming bot deleted it.

**Comment by johnpangalos** [comment]
This seems to have been deleted again. Is there any way of recovering it?
