### ISSUE TITLE
Request for clarification of the rules for filename matching

### ISSUE THREAD

**Issue by DA40** [editorconfig/editorconfig#445]
Given the difference between glob patterns "*" and "**", it seems that lookups can be for just the filename, and for the complete path and its subpaths.  Hence, for file "/dir1/dir2/file.ext", a match should be attempted against each of these, in the order given:

/dir1/dir2/file.ext
dir1/dir2/file.ext
dir2/file.ext
file.ext

If more than one match occurs, later ones take precedence. Is this interpretation of the specification correct?

Thanks

**Comment by xuhdev** [comment]
Yes. EditorConfig read `.editorconfig` from top to bottom, and applies the key-value pairs under each section when it matches. Later matches override earlier matches. For example,

```ini
[/dir1/dir2/file.ext]
indent_size = 2
tab_width = 2
[file.ext]
indent_size = 4
```

applying to `/dir1/dir2/file.ext` lead to:

```
indent_size = 4
tab_width = 2
```

**Comment by DA40** [comment]
Thanks for confirming.
