### ISSUE TITLE
## Licensing

### ISSUE THREAD

**Issue by MRGRAY0000** [editorconfig/editorconfig#453]
## Licensing
- [x] I provide my work under the [project license](https://github.com/progit/progit2/blob/main/LICENSE.asc).
- [x] I grant such license of my work as is required for the purposes of future print editions to [Ben Straub](https://github.com/ben) and [Scott Chacon](https://github.com/schacon).

## Changes

- Make it clear that the set of tracked files includes more than those in the latest commit.

__Originally posted by @bkline in https://github.com/progit/progit2/pull/1677__

**Comment by ffes** [comment]
Could you please explain what all your issues in this repository have to do with EditorConfig?

**Comment by florianb** [comment]
@ffes – seems like a bot.

**Comment by xuhdev** [comment]
Yes MRGRAY0000 sent a few spams yesterday. I've blocked this user now.
