### ISSUE TITLE
Include .editorconfig from other folder

### ISSUE THREAD

**Issue by Kasp42** [editorconfig/editorconfig#456]
In our team we have several repositories with projects and one shared repository with editor config and another general files and configs.

Structure:
Project A
  .editorconfig
Project B
  .editorconfig
Project N
  .editorconfig

Shared project(every developer has this reposioptry)
  .editorconfig

Shared project updated every when update any project.
Also shared repository placed on same level as another projects.

I would like to set in each projects for load config.
include=././shared/.editorconfig

**Comment by ffes** [comment]
Isn't this a dup of #236?

**Comment by cxw42** [comment]
I think it can be merged into #236.

**Comment by xuhdev** [comment]
Yes, you are right. Dup of #236
