### ISSUE TITLE
Tiny textual adjustment suggested.

### ISSUE THREAD

**Issue by EskeRahn** [editorconfig/editorconfig#458]
In your text here  https://editorconfig.org/  
There is a minor confusion between the textual punctuation of the sentence and the file-dot in this text:  

_For Windows Users: To create an .editorconfig file within Windows Explorer, you need to create a file named .editorconfig., which Windows Explorer will automatically rename to .editorconfig._  

Sure the two use a different font, but not easy to spot in all browsers. So users new to this general Windows-trick might not get it. Allow me to suggest a slight rewording, with something between the filename and the textual punctuations, say:  

_For Windows Users: To create an .editorconfig file within Windows Explorer, you need to create a file named .editorconfig. with a trailing dot, which Windows Explorer will automatically rename to .editorconfig for you._

**Comment by xuhdev** [comment]
Good point! How about 

> ... a file named .editorconfig. (note the trailing dot) ...

**Comment by EskeRahn** [comment]
Any words will do, the most important is at the end of the sentence ;)
