### ISSUE TITLE
XDG compliance

### ISSUE THREAD

**Issue by sakuro** [editorconfig/editorconfig#461]
[The lookup of .editorconfig](https://editorconfig.org/#file-location) does not honor [XDG specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

Any plans for supporting this?

Related: #236 #456

**Comment by greut** [comment]
So does  `.git` and it's perfectly fine. What would be the use case outside the issues you've mentioned?

**Comment by sakuro** [comment]
I can reduce clutter in my home directory if I can put the _root_ editor config under XDG compliant directory (say ~/.config by default).

**Comment by ffes** [comment]
Placing a `.editorconfig` in `$HOME` feels a bit strange to me. It only works in a limited set of scenarios, like when you want to use it for your files in your `$HOME`. You can do that obviously, but I don't see why that would the reason to support XDG.

This is the first line in the website:

> EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs.

Note the "multiple developers working on the same project". It was never designed to be a system wide thing for personal use.

When the source code is in a subdirectory in `$HOME` and there is no `.editorconfig` in your project or you don't have the `root=true` in your project `.editorconfig` falling back to your `$HOME/.editorconfig` is a bad idea and not something that should be supported.

And XDG is only a convention on Linux (and probably Mac, not sure). On Windows there is no such thing as XDG. In that case it should be placed somewhere in `%APPDATA%` or in `C:\ProgramData` or another hard to find directory.

So I don't see a reason to support XDG.

**Comment by sakuro** [comment]
OK I understand the rational.

**Comment by texastoland** [comment]
> So does `.gitignore` and it's perfectly fine.

FWIW Git's default global ignore on Linux/Mac is `$XDG_CONFIG_HOME/git/ignore`.
