### ISSUE TITLE
Feature Request: Merge several .editorconfig files on the same directory level

### ISSUE THREAD

**Issue by anreton** [editorconfig/editorconfig#462]
**Description**

I have one file with settings for different static analyzers for C# (StyleCop, SonarLint, Roslynator, XUnit, etc). And the file size already reaches 5000 lines.

It would be convenient to split one file into several for more grouping and handy work.

For instance:
- .editorconfig - for general things
- roslynator.editorconfig - for Roslynator things
- stylecop.editorconfig - for StyleCop things
- etc.

**Comment by cxw42** [comment]
Would #236 cover your use case?  If so, I would like to close this issue as a duplicate.  If not, would you please give an example of the syntax and file layout you would like to see?  Thanks!

**Comment by anreton** [comment]
@cxw42, Thank you for your response.

Yes, you are right, #236 covers my case.
