### ISSUE TITLE
Attitude towards "extensions"

### ISSUE THREAD

**Issue by ameenross** [editorconfig/editorconfig#463]
I'm not entirely sure whether this is the correct repository for my question, but here goes.

IntelliJ has decided to put a whole bunch of their own options in their implementation of `.editorconfig`. That seems to me to be contrary to the entire idea of Editorconfig, in that there's a common set of basic formatting options that is editor agnostic. These extensions are not editor agnostic and don't even pretend to be, as they are prefixed `ij` which presumably stands for IntelliJ. For example `ij_php_align_phpdoc_param_names`. This feels to me to be a case of ["embrace, extend, extinguish"](https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish).

What is the opinion of the community?

**Comment by xuhdev** [comment]
I think this is OK as long as their own options don't clash with the standard ones, because the purpose of EditorConfig is to offer consistency for people using different editing programs. In fact, the file format is designed in a way that each editor plugin can add their own things. You can have an independent formatter for each programming language, but as a very generic tool, EditorConfig can't be that powerful.

**Comment by cxw42** [comment]
Related to #415

**Comment by ameenross** [comment]
Alright, so I did a little bit of reading, and I'm still rather against the `ij_foo` options. I do recognize that options for language specific formatters *could* be useful. However, all JetBrains have done is port some configuration of their proprietary editor to EditorConfig. This is never going to work for anyone *not* using IntelliJ, nor is it possible to use as a basis for a PHP specific formatter.

If EditorConfig is going to become a more thorough code style tool then JetBrains certainly didn't help that cause, it only muddied the waters. It seems more appropriate to use existing (non-proprietary and standalone) formatters, like phpcs, eslint and whatnot, as a basis.

**Comment by cxw42** [comment]
I am closing this issue as the answer is "yes, custom keys are OK" :) .  More discussion about naming standards for custom keys is at #332.
