### ISSUE TITLE
Willing to join the team!

### ISSUE THREAD

**Issue by jcs090218** [editorconfig/editorconfig#470]
Hi, editorconfig team!

l've recently started using this plugin and I really love it! I would like to ask to see if I could join the team and contribute/maintain some plugins (I'm using Emacs, so mainly to Emacs' package).

A little bit of myself, I have developed 40+ elisp packages and maintain 70+ of them. I would say I'm very familiar with elisp, and the Emacs package development. From all my experiences in the past, I reckon I'm pretty good at cross-platform CI/CD (GHA only). Pleas check out my GitHub profile if you want to know more about my work! Hope I can be helpful somehow. ;)

**Comment by xuhdev** [comment]
Thank you for your interest! Feel free to send PRs when you see something to work on :) We can get you committer status once you have made some contributions
