### ISSUE TITLE
ignore directories?

### ISSUE THREAD

**Issue by brianbcampbell** [editorconfig/editorconfig#471]
I have a directory which contains autogenerated code. When the generator runs, the directory is wiped and repopulated. I'd rather not drop an ec file there.
In the ec file mask, can I use NOT? 
Maybe like 
`[{*.java},!{*/service/model/*}]`

**Comment by cxw42** [comment]
Could you tell us more about the use case?  Since the files are generated, do you usually edit them?  What is the negative effect of having your `*.java` rules apply to the generated java files?

**Comment by SimonHeimberg** [comment]
Some use cases and ways to handle this: https://stackoverflow.com/questions/30310396/possible-to-ignore-exclude-file-folder-from-editorconfig

Solution I see as best matching:
```
[*.java]
end_of_line = lf

[*/service/model/*]
# unset all undesired settings
end_of_line = unset
```
