### ISSUE TITLE
Are settings merged?

### ISSUE THREAD

**Issue by scarf005** [editorconfig/editorconfig#473]
I think it does, for example if i 
```
[*]
end_of_line = lf

[*.json]
indent_size = 4
```
then editorconfig for `*.json` would be
```
end_of_line = lf
indent_line = 4
```
however it's poorly explained in [official docs](https://editorconfig.org/), it just shows some example use cases and doesn't explicitly states the sub-settings are merged. It'd be great to add doc for it.

**Comment by greut** [comment]
> EditorConfig files are read top to bottom and the most recent rules found take precedence. Properties from matching EditorConfig sections are applied in the order they were read, so properties in closer files take precedence.

and, again,

> EditorConfig files are read top to bottom and the most recent rules found take precedence.

----

Do you have any suggestion how to improve that?

**Comment by scarf005** [comment]
well, maybe because english is not my native langauge, but I don't see how `read from top to bottom`, `recent rules take precdedence` mean that rules from broader patterns get coerced into narrower patterns.

> rules from broader wildcard patterns (e.g: [*]) are applied to narrow wildcard patterns (e.g: [*.json])

I think adding one line would make it more clear.

**Comment by greut** [comment]
> All rules from broader wildcard patterns (e.g: [*]) are applied to narrow wildcard patterns (e.g: [*.json]).

It's not CSS, they are applied _in the order they were read_, so **last one wins**.

**Comment by scarf005** [comment]
then do you mean if given configuration of
```
[*]
tab_size: 4
indent_size: 4

[*.json]
indent_size: 2
```
the settings for `*.json` would not be
```
tab_size: 4
indent_size: 2
```
but
```
indent_size: 2
```
?

**Comment by greut** [comment]
> Properties from matching EditorConfig sections are applied in the order they were read

Take any editorconfig tool, e.g. [the Go one](https://github.com/editorconfig/editorconfig-core-go/releases/tag/v2.5.1)

```ini
[*]
indent_size = 4

[*.json]
indent_size = 2

[bar.*]
indent_size = 6
```

And try it.

```console
$ editorconfig foo.tx foo.json bar.json
```

<details>
<summary>spoilers</summary>

```ini
[foo.txt]
indent_size=4
tab_width=4
[foo.json]
indent_size=2
tab_width=2
[bar.json]
indent_size=6
tab_width=6
```

</details>

**Comment by scarf005** [comment]
```
# .editorconfig
[*]
insert_final_newline = true
indent_size = 2

[*.py]
indent_size = 4
```

```
[/home/scarf/Downloads/foo.txt]
insert_final_newline=true
indent_size=2
tab_width=2

[/home/scarf/Downloads/foo.py]
insert_final_newline=true
indent_size=4
tab_width=4
```

so the settings does get merged, albeit only the last one matters.
