### ISSUE TITLE
Invatiton 

### ISSUE THREAD

**Issue by arroselli** [editorconfig/editorconfig#474]
Sign up for Coinbase using my link and we can each get €10.13 in Bitcoin https://coinbase.com/join/lem3i8?src=android-link

**Comment by Pittan** [comment]
Seems to be a spam, closing

**Comment by greut** [comment]
Can anybody delete it? Reporting it as spam does nothing :sob:

**Comment by Pittan** [comment]
Maybe admin role can delete this.
https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue
