### ISSUE TITLE
Feature Request: Strip multiple blank lines from the end of the file

### ISSUE THREAD

**Issue by drenze-athene** [editorconfig/editorconfig#483]
# Use Case

As a user of editorconfig, I frequently edit files with a long string of newlines at the end of the file or accidentally insert multiple newlines at the end of the file. It would be helpful to have a setting which would allow me to strip multiple newlines from the end of the file to ensure that it ends with one and only one newline.

# Details

As a user, this is a minor annoyance to me. In the same way that trailing whitespace often accretes on lines in a text file, trailing newlines frequently end up at the end of a file, so that I save it with a single newline, the next time I check out a branch there are three trailing newlines, and by the third time I check it out there are a dozen.

I propose one of two ways to handle this:

```
trim_multiple_final_newlines = (true|false)
```

This would ensure that there is never more than a single newline at the end of a file. However, acknowledging that there may be valid use cases for multiple final newlines at the end of the file, a preferred method would be:

```
final_newline_count = N
```

N is the number of blank lines at the end of the file. In this case:

* `N = 0` would leave no newlines at the end of the file.
* `N = 1` would leave one and only one newline at the end of the file, simulating the `insert_final_newline = true` for a file without a trailing newline.
* `N = 5` would leave five and only five newlines at the end of the file.
* Etc.

If either solution is approved for incorporation into editorconfig, the specific declaration name is not important, only the behavior (indeed, it should be aligned to current schema naming conventions).

**Comment by florianb** [comment]
Hi @drenze-athene - thank you for taking the time filing the feature request. This feature should already be implemented by the `insert_final_newline`, as stated in the issue #475.

I guess we need to clarify the specification to reflect the intend - it then is finally to the plugin developers (and the editor features) to allow the implementation.

**Comment by xuhdev** [comment]
Closing this, thank you for reporting!
