### ISSUE TITLE
Neovim editorconfig integration

### ISSUE THREAD

**Issue by jneidel** [editorconfig/editorconfig#484]
https://neovim.io/doc/user/editorconfig.html :tada: 

Neovim now has builtin editorconfig integration and should be added to the list of "No Plugin Necessary" editors.

**Comment by xuhdev** [comment]
Awesome! @Pittan Would you be able to help again :) Thank you!

**Comment by qubidt** [comment]
Worth nothing that this was introduced in https://github.com/neovim/neovim/pull/21633, and has not yet been included in a [stable release](https://github.com/neovim/neovim/releases/tag/stable). It'll most probably require at least v0.9 (current: v0.8.3)

**Comment by dtomvan** [comment]
Neovim v0.9 [just got released](https://github.com/neovim/neovim/releases/tag/v0.9.0) :tada:

**Comment by treyhunner** [comment]
The logo was added to the "no plugins necessary" section in editorconfig/editorconfig.github.com#174 🎉
