### ISSUE TITLE
cpp_space_before_inheritance_colon not interpreting correctly

### ISSUE THREAD

**Issue by amaier17** [editorconfig/editorconfig#485]
The extension for vscode doesn't seem to be interpreting the cpp_space_before_inheritance_colon correctly. By definition this is supposed to "Insert space before colon for base in type declarations" however for an enum type it doesn't seem to be doing this. This is supposed to put a space around the colon like this:

```
enum MyEnum : int
{
....
}
```

However it is removing the space before the colon:
```
enum MyEnum: int
{
....
}
```

**Comment by florianb** [comment]
Hi @amaier17 - thanks for getting in touch.

`cpp_space_before_inheritance_colon` is no *official* setting of EditorConfig and this is not the repository in charge of the VSCode plugin. Please consider reopening the issue somewhere else.

The issue you're searching for might be https://github.com/microsoft/vscode-cpptools/issues/10263

**Comment by sean-mcmanus** [comment]
This issue can be closed. It'll be fixed in the 1.15.2 (pre-release) update of the C/C++ extension.

**Comment by xuhdev** [comment]
Please refer to https://github.com/microsoft/vscode-cpptools/issues/10263. Closing now.
