### ISSUE TITLE
Wiki link to `EditorConfig-Properties` is 404

### ISSUE THREAD

**Issue by silverwind** [editorconfig/editorconfig#488]
https://editorconfig.org/#file-format-details#supported-properties contains a link to https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties but this wiki page no longer seems to exist. Is there a replacement page?

**Comment by silverwind** [comment]
Thanks. Should probably move important content like this to repo files to protect them better.

**Comment by xuhdev** [comment]
We have more formal specifications at https://spec.editorconfig.org/#supported-pairs

But we don't want users to be too bothered with all the standardese and we do not link to it from the user's sections on the homepage.
