### ISSUE TITLE
[Question] - line endings git attributes and editor config

### ISSUE THREAD

**Issue by dazinator** [editorconfig/editorconfig#489]
Since #226 was closed and won't be implemented,

I am wondering what the recommended solution is for this basic problem with line endings:

1. `gitattributes` is specifying `auto` - i.e so `.cs` files get checked out as `CRLF` in windows and `LF` on linux
2. `editorconfig` is `CRLF`
3. `dotnet format` succeeds locally for windows developers, but fails with line endings checks on linux servers.

I have used pretty common "best practice" settings individually for `gitattributes` and `editorconfig`. I say that because the tools and [docs](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#example) on git attributes all tend to suggest setting `source code` files like `.c` or `.cs` to `auto` which means they will be checked out with CRLF on windows and LF on linux. This enables for example, developers on linux too edit source code without having their tools complain about windows style line endings, and vice versa. Howevert this would seemingly make a `static` setting such as `end_of_line = crlf` in the `editorconfig` kind of problematic?

Some avenues I thought of:

1. support `native` line endings as proposed by #226 ( but this was closed after a vote - any chance to reconsider?)
2. chage editor config line endings settings to something else - but none of these ones would seem to help?  
![image](https://github.com/editorconfig/editorconfig/assets/3176632/363865b7-650c-4476-8d21-83afe300c84f)

3. change `.gitattributes` so that line endings are `CRLF` for any files which `editorconfig` also applies to..  But this means on checkout too linux machines, a linux developers editor that doesn't support CRLF may now break,, even though `dotnet format` should now pass. 

So I am seeking guidance here. What is the recommended solution?

**Comment by xuhdev** [comment]
If I understand git's autocrlf correctly, setting it to auto would let `git` normalize the line endings it saves in the index: https://git-scm.com/docs/gitattributes#_end_of_line_conversion

This should imply that you can use whatever line endings you like and it won't affect the EOL saved by git.

Do you control the `.editorconfig` file of the project? If so, I would recommend removing the `end_of_line` settings in EditorConfig because it sounds like your project does not have a uniform EOL requirement for the **files in the working directory across platforms**.

**Comment by dazinator** [comment]
@xuhdev removing `end_of_line` from `.editorconfig` and relying on git to normalise line endings sounds like a good plan. We will give this a go! thank you.

**Comment by tlunsfordCXP** [comment]
Removing `end_of_line` works well. Except that in Visual Studio, any time I open editorconfig, it is compelled to set the value back. I'm continually battling it.
