### ISSUE TITLE
Forbid section names ending with a slash

### ISSUE THREAD

**Issue by cxw42** [editorconfig/editorconfig#493]
A section name should never end with a slash, since EditorConfig settings only apply to files (per the spec).  However, I don't see that we have tests or spec language stating that.  I think we should add those tests and that language.

Proposed spec change: in <https://spec.editorconfig.org/#glob-expressions>:
```diff
 ... through Unix shell-style wildcards. 
+These filepath globs match files, not directories.  
+Therefore, a section name must not end with a `/`.
-These filepath globs 
+The filepath globs
 recognize the following as special characters for wildcard matching:

**Comment by xuhdev** [comment]
I'm not sure if we want to say "a section name must not end with a `/`". Based on what we have, it sounds like a `/`-ended section name simply won't match anything. I opened https://github.com/editorconfig/specification/pull/58; let me know what you think
