### ISSUE TITLE
Should `key =` be considered valid (meaning `key` is set to empty string)?

### ISSUE THREAD

**Issue by ppalaga** [editorconfig/editorconfig#496]
This is what the current [specification](https://spec.editorconfig.org/) says:

> Each line must be one of the following:
> ...
> * Key-Value Pair (or Pair): contains a key and a value, separated by an =.
>   * Key: The part before the first = (trimmed of whitespace, but including any whitespace in the middle).
>   * Value: The part after the first = (trimmed of whitespace, but including any whitespace in the middle).
> Any line that is not one of the above is invalid.

I wonder whether it may be interpreted in such a way that `key =` (without value) is legal and means that `key` is set to empty string?

If so we should add some tests to https://github.com/editorconfig/editorconfig-core-test

There are some related discussions in https://github.com/ec4j/editorconfig-maven-plugin/issues/150 and https://github.com/ec4j/ec4j/issues/123 where users of IntelliJ style export mention that IntelliJ exports keys without values.

cc @vitalijr2 @Vampire

**Comment by vitalijr2** [comment]
Yeah, for me looks like a pair is invalid if it doesn't have at least one equal sign which split this pair to key and value.
The specification doesn't contain requirements for minimal length and even allow an empty key (but I think it is very strange case).

**Comment by Vampire** [comment]
Why ignoring and not supporting empty value? Empty value is different to entry absence. Empty key is indeed questionable though.

**Comment by ppalaga** [comment]
@vitalijr2 @Vampire BTW, what is the meaning of `key =` in those IJ style exports? Is it really an empty string, rather than value not set?

**Comment by Vampire** [comment]
I'd say so, yes.
If it is absent, the value from the code style settings is used.
If it is set to empty, then empty value is used.
For example if you look at `ij_java_packages_to_use_import_on_demand` which in the UI is "Packages to Use Import with '*'".
If the property is missing from `.editorconfig`, IntelliJ uses what is configured in the UI.
If the property is set to an empty value in `.editorconfig`, IntelliJ uses an empty value.

**Comment by cxw42** [comment]
`key=` looks surprising to me, but since the spec doesn't define escaping, I think it is the clearest way to express an empty-string value.  I agree with clarifying the spec and tests to expressly allow empty values.

Assuming the empty-value match is something like `/^\w+\h*=\h*$/`, I think it would also be worth mentioning in the spec that a value consisting only of whitespace is not supported, since the whitespace will be trimmed.

Empty keys (`=foo`) should be forbidden, since they have no semantics in EditorConfig at present.

**Comment by ppalaga** [comment]
Here is a proposal how we could test it: https://github.com/editorconfig/editorconfig-core-test/pull/52

**Comment by ppalaga** [comment]
@cxw42 would you like to propose the change in the spec?

**Comment by cxw42** [comment]
The core tests and the spec changes are now merged.

**Comment by ppalaga** [comment]
Thanks everybody! I have just released ec4j implementing the newly standardized behavior
