### ISSUE TITLE
Spec clarification: "should" -> "must" be utf-8

### ISSUE THREAD

**Issue by cxw42** [editorconfig/editorconfig#497]
The spec [says](https://spec.editorconfig.org/#file-format):
> EditorConfig files should be UTF-8 encoded...

I think this should say
> EditorConfig files must be UTF-8 encoded...

("must" instead of "should") for the avoidance of any doubt.  Let me know if you have any concerns!  I'll open a spec PR in due course.

**Comment by ffes** [comment]
I agree.

Should it also mention "without a BOM"?

**Comment by cxw42** [comment]
@ffes I just checked, and the C core accepts files with BOM.  Therefore, I do not think we should outlaw BOM.  (I don't think it's worth a breaking change.)

Ref.: https://github.com/editorconfig/editorconfig-core-c/blob/2d5b4fe61a3d7f7f154c61b2c1d8d741fe29048c/src/lib/ini.h#L84-L88
