### ISSUE TITLE
How to have different setting for different platforms?

### ISSUE THREAD

**Issue by shaishasag** [editorconfig/editorconfig#502]
I would like to use the same .editorconfig file for MacOS, Windows and Linux users.
Windows user need:
`end_of_line = crlf`
while MacOS and Linux users need:
`end_of_line = lf`

Is there a way to have different setting for each platform?

**Comment by xuhdev** [comment]
This was discussed before at https://github.com/editorconfig/editorconfig/issues/226#issuecomment-343961943 . Unfortunately, we thought it wasn't suitable for EditorConfig to support this feature and the situation hasn't changed materially. I'm closing this for now and feel free to comment if you have any thoughts.
