### ISSUE TITLE
Question: Are generally unsupported properties breaking?

### ISSUE THREAD

**Issue by RobertoRoos** [editorconfig/editorconfig#504]
In a nutshell: is it safe to add custom .editorconfig properties to my own tool>

I am making a formatting tool for TwinCAT PLC files. For my formatter I need some kind of user configuration file, to decide on the style. I figured using an existing config file, like .editorconfig, would be more convenient for users than designing yet another new file type.
EditorConfig already has some properties I am interested in, like `indent_style` and `indent_size` for instance. But there are also settings I want to add that are not official, e.g. `align_variables`=`true/false`.
My question: will adding unofficial properties to my .editorconfig generally break other existing parsers?

(Apologies if this is asked in the wrong place, I didn't see a 'discussions' tab or similar.)

**Comment by ffes** [comment]
In general it shouldn't break existing properties.

Various others (like [MS for .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options) and [JetBrains](https://www.jetbrains.com/help/idea/editorconfig.html)) have introduced their own properties.

When you start using your own properties it is wise to give them a prefix, something like `twincat_align_variables = true`. This way they are unique for your application and wouldn't break anything.

**Comment by RobertoRoos** [comment]
Good suggestion, that's what I was hoping for.

**Comment by xuhdev** [comment]
As @ffes has answered, unknown properties are passed through by the core libraries. This is supported in the [spec](https://spec.editorconfig.org/#supported-pairs):



>    - EditorConfig cores shall accept and report all syntactically valid key-value pairs, even if the key is not defined in this specification.

>    - EditorConfig plugins shall ignore unrecognized keys and invalid/unsupported values.
