### ISSUE TITLE
Meaning of a glob like `a/*.c`

### ISSUE THREAD

**Issue by monnier** [editorconfig/editorconfig#509]
Let's say we have a section whose glob looks like `*.c` in a `/foo/.editorconfig`.  AFAICT this section will apply to any file matching the glob `/foo/**/*.c`, right?

What about `a/*.c`?  Will it match files of the form `/foo/**/a/*.c` or only `/foo/a/*.c`?
Is there a way to have a section that applies only to files of the form `/foo/*.c` (i.e. to C files in `/foo` but not in subdirectories)?
The spec says *very* little about these things.

**Comment by xuhdev** [comment]
I agree this is indeed confusing. The spec intends to say that the rules are similar to those used by `.gitignore`. Therefore, `a/*.c` doesn't match `foo/a/a.c`. This is the part of [gitignore](https://git-scm.com/docs/gitignore) that we follow:

> If there is a separator at the beginning or middle (or both) of the pattern, then the pattern is relative to the directory level of the particular .gitignore file itself. Otherwise the pattern may also match at any level below the .gitignore level.

We should make this clear and add it to the spec and tests.

**Comment by cxw42** [comment]
@xuhdev In `core-test:glob/CMakeLists.txt`, I see:
```
# star after a slash
new_ec_test_multiline(star_after_slash_ML star.in Bar/foo.txt "keyb=valueb[ \t\n\r]+keyc=valuec[ \t\n\r]*")

# star matches a dot file after slash
new_ec_test_multiline(star_matches_dot_file_after_slash_ML star.in Bar/.editorconfig "keyb=valueb[ \t\n\r]+keyc=valuec[ \t\n\r]*")
```
I think we need to add tests for `... bat/Bar/foo.txt` and `... bat/Bar/.editorconfig` _not_ matching.  Does that match your understanding?

**Comment by cxw42** [comment]
Reopening to finish the discussion about the tests

**Comment by xuhdev** [comment]
Yes, I agree. Could you create the PR?
