### ISSUE TITLE
Re: EpicEditor Website Link in Wiki

### ISSUE THREAD

**Issue by em-deltaxp** [editorconfig/editorconfig#510]
It seems that the link for EpicEditor on this page in the wiki: 
[Projects Using EditorConfig · editorconfig/editorconfig Wiki](https://github.com/editorconfig/editorconfig/wiki/Projects-Using-EditorConfig)
which should, by all appearances, refer to the EpicEditor development or product website, is actually now just linking to what looks like a parked domain doing some generic keyword advertising, with no connection to the EpicEditor project whatsoever.

Just thought someone might want to know about it, that's all.

**Comment by xuhdev** [comment]
It's the same as the one on its GitHub page: https://github.com/OscarGodson/EpicEditor/tree/develop Maybe it's temporary.

**Comment by xuhdev** [comment]
Looks like this is relevant: https://github.com/OscarGodson/EpicEditor/issues/402

I removed the link for now. Thanks for reporting!
