### ISSUE TITLE
[FEATURE] Add charset OEM 850 and ANSI encoding

### ISSUE THREAD

**Issue by bege10** [editorconfig/editorconfig#519]
## Which problem does this feature fix?
Save Windows users from constant need to change encoding manually. BAT and CMD files are always opened with ANSI encoding in Notepad++. I always must manually change encoding to OEM 850.

## Describe the solution you'd like
OEM 850 and ANSI as standard Windows/DOS encodings should be supported.

## Additional context
I thought enditorconfig would support all encodings provided in Notepad++, but https://editorconfig.org/#file-format-details shows there are only these few "latin1", "utf-8", "utf-8-bom", "utf-16be" or "utf-16le".
That is probably the reason why enditorconfig shows the correct charset settings from .editorconfig but does not change them.

**Comment by florianb** [comment]
Hi @bege10 - did you already try if Notepad++ accepts file-format-values (in addition to the few from the specification)?

I think widening the charsets in the specification is easy to do (since it won't carry out the risk of any backward incompatibilities).

@xuhdev - any obligations about thinking to widen the supported charsets?

**Comment by bege10** [comment]
> Hi @bege10 - did you already try if Notepad++ accepts file-format-values (in addition to the few from the specification)?

Yes, as I tried to explain above.
![Screenshot_002](https://github.com/user-attachments/assets/96113012-313b-4abc-804a-29c81813dcf2)

**Comment by ffes** [comment]
I have never ran into any problem with batch files in utf8 encoding, but apparently this is a problem for you.

As you rightfully mentioned, the editorconfig specs don't mention `oem850` or `ansi`, and therefore the notepad++ plugin doesn't support them. But know that for the notepad++ plugin `latin1` is the same as your `ansi`.

You could also try to add this section to your `editorconfig`:

```ini
[*.bat]
charset = unset
```

I haven't tested this for the notepad++ plugin, but [looking at the code](https://github.com/editorconfig/editorconfig-notepad-plus-plus/blob/0539ff1b2cd475397dec364e4e1642bfb3e5672d/src/PluginDefinition.cpp#L324) it should leave the charset untouched.  If not, please file a bug in that repository.

**Comment by ffes** [comment]
To keep discussion about additional charsets in one place, I would suggest to close this one in favor of #467 and make a list what charsets to add.

**Comment by bege10** [comment]
@ffes utf-8 in Windows batch files is an issue if you have German umlauts in it.

Meanwhile the plugin AutoCodepage works correct and solves the issue for me.
As you suggest I will close this issue. Thanks!
