### ISSUE TITLE
Any plans for a Eclipse or Net Beans plugin

### ISSUE THREAD

**Issue by nschonni** [editorconfig/editorconfig#86]
Really liking this in NPP and VS, but some team members use Eclipse and Net Beans.
Any plans on supporting any of these IDEs?

Edit: noticed there is an issue tag for Eclipse

**Comment by treyhunner** [comment]
@bennyn and @Yserz: any update on the NetBeans plugin?

We're happy to tweet/retweet a call for testers/developers or anyone else who might be able to help out if/when you're looking for community help.

**Comment by bennyn** [comment]
Hey @treyhunner, I am glad that you ask. 

We could in fact need some help! We solved already some issues and are able to parse EditorConfig files. In terms of functionality, we are also pretty far. We know how to set the tab width, indent style and indent size. We can also insert a final new line and trim trailing whitespaces. 

What's missing is to save the file in a different encoding. We know how to detect the current encoding but from NetBeans we are not able to save it in a different encoding. This is where we can use some help.

Here is a screenshot of the plugin in action:

![](https://dl.dropboxusercontent.com/u/74217418/screenshots/github/editorconfig-plugin/screen-1.png)

**Comment by treyhunner** [comment]
@bennyn I wouldn't worry about not including `charset` support initially.

All of the following plugins do not claim `charset` support in their README files:
- [Brackets](https://github.com/kidwm/brackets-editorconfig/)
- [Code::Blocks](https://github.com/editorconfig/editorconfig-codeblocks#readme)
- [Emacs](https://github.com/editorconfig/editorconfig-emacs#readme)
- [Geany](https://github.com/editorconfig/editorconfig-geany#readme)
- [Gedit](https://github.com/editorconfig/editorconfig-gedit#readme)
- [Notepad++](https://github.com/editorconfig/editorconfig-notepad-plus-plus#readme)
- [TextMate](https://github.com/Mr0grog/editorconfig-textmate#readme)
- [Visual Studio](https://github.com/editorconfig/editorconfig-visualstudio#readme)

Are all of the other options already supported?

**Comment by lipis** [comment]
Yes @bennyn! If the rest is working reliably do it.. encoding is something very invisible anyway, while the rest is pretty cool to have.. :dancers:

**Comment by xuhdev** [comment]
@bennyn Don't worry, you can already release it when it works for the core functionalities (such as `indent_style`, `indent_size` `tab_width`) it should be good to release. By releasing it, you will get more feedback, thus the other features can be added more easily.

**Comment by bennyn** [comment]
I just updated our README file: https://github.com/welovecoding/editorconfig-netbeans

The properties `indent_size`, `indent_style`, `insert_final_newline` and `trim_trailing_whitespace` are reliably working. I will implement `tab_width` on the weekend and @Yserz has an approach for `end_of_line`.

If we get `tab_width` and `end_of_line` implemented, then we can go for a first release! :smiley:

**Comment by bennyn** [comment]
**Good news!** We implemented all properties except "charset" in https://github.com/welovecoding/editorconfig-netbeans.

Now we need some techy beta testers! :smiley:

**Comment by lipis** [comment]
Looking forward to cover this little empty space :) :dancers: :dancer: :dancers:

**Comment by treyhunner** [comment]
:tada: @bennyn excellent!

Do you mind if we merge editorconfig/editorconfig.github.com#14 and Tweet about the plugin?  We can note that it's in beta, but it's difficult to find testers if people don't know it exists yet.

**Comment by apennebaker-ni** [comment]
+1

**Comment by bennyn** [comment]
Hey @treyhunner, thanks for being so patient with us. 

@yserz and I have just built a beta release. We also added a beta disclaimer to draw attention to the status of the plugin. You can now advertise the plugin. That would make us very happy. :smiley: 

The installable NetBeans module  (`*.nbm`) can be downloaded here:
https://github.com/welovecoding/editorconfig-netbeans/tree/master/dist

Best from Berlin,
Benny

**Comment by treyhunner** [comment]
The NetBeans plugin is now listed on the website!  I'm sending out a tweet about it in a few minutes.

**Comment by bennyn** [comment]
Great! So happy to see the NetBeans logo on the EditorConfig homepage. :dancers:

**Comment by treyhunner** [comment]
I am closing this issue as resolved since we already have #108 for an Eclipse plugin. :fireworks:
