### ISSUE TITLE
Define a formal grammar for EditorConfig file format

### ISSUE THREAD

**Issue by treyhunner** [editorconfig/editorconfig#98]
Relevant mailing list discussion: https://groups.google.com/forum/?fromgroups=#!searchin/editorconfig/grammar/editorconfig/ZBd9S4uGsWQ/lBMPR5smE9wJ
##

**Comment by markus2330** [comment]
May I propose to consider [Elektra](https://www.libelektra.org) as a general framework for accessing configuration files?

It seems to solve the problems you have:

- We support hierarchy (also with INI: by having sections within sections)
- it supports formally specified configuration file formats (XML, JSON, and hopefully soon YAML)
- It allows us to output the config in any of the supported formats, like JSON as requested in #67
- We have much more tooling for editing and [validating](https://www.libelektra.org/tutorials/validate-configuration) configs. The [FAQ](https://github.com/editorconfig/editorconfig/wiki/FAQ) mentions EditorConfig's tooling has some problems.

And Elektra seems to be completely compatible with what you are currently have (it supports format-preserving INI and using the [dir namespace](https://www.libelektra.org/manpages/elektra-namespaces) the config file is searched recursively in the current working directory and above).

We have not yet released 1.0, which is an advantage (you have much more influence how it should be), but also an disadvantage (we plan to change things). If you are interested, we can start testing with your files and help you with migration.

Btw. I really like your project and hope much more of such projects pop up to unify everything else (like keyboard shortcuts, languages, favourite directories, ...). It won't work if every of these project needs to start by defining a new configuration file format.

I look forward to hearing from you. I hope it is okay that I hijacked this old issue. I can open a new with more concrete suggestions if preferred.

**Comment by jedmao** [comment]
@markus2330, am I missing something? Elektra says it's cross-platform, but there are no binaries for Windows. Am I mistaken? I've been searching the docs and see no mention of Windows, in fact.

One of the cool things about EditorConfig, in my mind, is that there are separate cores for Python, JavaScript, etc.; yet, they all pass the same tests. For example, I like knowing that I can run the JavaScript core in Node.js w/o compiling anything or depending on any other languages. It's a rather painless experience.

For your 1.0 release, I suggest tackling these same problems. This might require you build separate cores as well.

**Comment by jedmao** [comment]
Shared tests are at https://github.com/editorconfig/editorconfig-core-test

It looks like there are currently 8 cores. I think it's a beautiful idea, because we are comfortable knowing that all the cores support the exact same features via the tests.

**Comment by treyhunner** [comment]
Using TOML recently for a project and I realized how similar it is to the INI flavor used by EditorConfig.

It looks like TOML has [a formal grammar](https://github.com/toml-lang/toml/blob/master/toml.abnf). Maybe we can steal a subset of it (which would need to be modified to accept string literals without quotes and to not treat quotes specially in general) for EditorConfig.

Aside: I considered opening an issue to propose supporting TOML in `.editorconfig` files, but the string syntax is different and I'm not actually too interested in starting that discussion. If anyone else would like to weigh pros and cons for a "support TOML" discussion I might chime in though.

**Comment by cxw42** [comment]
Can this now be closed in favor of editorconfig/specification and its rendered output at https://editorconfig-specification.readthedocs.io/en/latest/ ?  That is now the official spec per #361.

**Comment by xuhdev** [comment]
Yes. Closing now.
